
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.extrabuildingblocks.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.extrabuildingblocks.block.YellowStainedSoulGlassPaneBlock;
import net.mcreator.extrabuildingblocks.block.YellowStainedSoulGlassBlock;
import net.mcreator.extrabuildingblocks.block.YellowLaceCarpetBlock;
import net.mcreator.extrabuildingblocks.block.YellowLaceBannerBlock;
import net.mcreator.extrabuildingblocks.block.WroughtIronBarsBlock;
import net.mcreator.extrabuildingblocks.block.WhiteStainedSoulGlassPaneBlock;
import net.mcreator.extrabuildingblocks.block.WhiteStainedSoulGlassBlock;
import net.mcreator.extrabuildingblocks.block.WhiteLaceCarpetBlock;
import net.mcreator.extrabuildingblocks.block.WhiteLaceBannerBlock;
import net.mcreator.extrabuildingblocks.block.WeatheredWroughtIronBlock;
import net.mcreator.extrabuildingblocks.block.WeatheredCopperBarsBlock;
import net.mcreator.extrabuildingblocks.block.WarpedBeamBlock;
import net.mcreator.extrabuildingblocks.block.VeryCrackedStoneBricksBlock;
import net.mcreator.extrabuildingblocks.block.VeryCrackedBricksBlock;
import net.mcreator.extrabuildingblocks.block.TESTBlock;
import net.mcreator.extrabuildingblocks.block.SwampvineBlock;
import net.mcreator.extrabuildingblocks.block.SwampGrassBlock;
import net.mcreator.extrabuildingblocks.block.StonePillarBlock;
import net.mcreator.extrabuildingblocks.block.SpruceBeamBlock;
import net.mcreator.extrabuildingblocks.block.SoulSlateBricksBlock;
import net.mcreator.extrabuildingblocks.block.SoulSlateBrickWallBlock;
import net.mcreator.extrabuildingblocks.block.SoulSlateBrickStairsBlock;
import net.mcreator.extrabuildingblocks.block.SoulSlateBrickSlabBlock;
import net.mcreator.extrabuildingblocks.block.SoulSlateBlock;
import net.mcreator.extrabuildingblocks.block.SoulSconceBlock;
import net.mcreator.extrabuildingblocks.block.SoulMagmaBlock;
import net.mcreator.extrabuildingblocks.block.SoulLampBlock;
import net.mcreator.extrabuildingblocks.block.SoulGlassPaneBlock;
import net.mcreator.extrabuildingblocks.block.SoulGlassBlock;
import net.mcreator.extrabuildingblocks.block.SmoothStoneWallBlock;
import net.mcreator.extrabuildingblocks.block.SandstoneBricksBlock;
import net.mcreator.extrabuildingblocks.block.SandstoneBrickWallBlock;
import net.mcreator.extrabuildingblocks.block.SandstoneBrickStairsBlock;
import net.mcreator.extrabuildingblocks.block.SandstoneBrickSlabBlock;
import net.mcreator.extrabuildingblocks.block.SaltGrowthBlock;
import net.mcreator.extrabuildingblocks.block.SaltCrystalEmissiveBlock;
import net.mcreator.extrabuildingblocks.block.SaltCrystalBlock;
import net.mcreator.extrabuildingblocks.block.RustedWroughtIronBlock;
import net.mcreator.extrabuildingblocks.block.RedStainedSoulGlassPaneBlock;
import net.mcreator.extrabuildingblocks.block.RedStainedSoulGlassBlock;
import net.mcreator.extrabuildingblocks.block.RedSandstoneBricksBlock;
import net.mcreator.extrabuildingblocks.block.RedSandstoneBrickWallBlock;
import net.mcreator.extrabuildingblocks.block.RedSandstoneBrickStairsBlock;
import net.mcreator.extrabuildingblocks.block.RedSandstoneBrickSlabBlock;
import net.mcreator.extrabuildingblocks.block.RedLaceCarpetBlock;
import net.mcreator.extrabuildingblocks.block.RedLaceBannerBlock;
import net.mcreator.extrabuildingblocks.block.RawSaltBlock;
import net.mcreator.extrabuildingblocks.block.QuartzBrickWallBlock;
import net.mcreator.extrabuildingblocks.block.QuartzBrickStairsBlock;
import net.mcreator.extrabuildingblocks.block.QuartzBrickSlabBlock;
import net.mcreator.extrabuildingblocks.block.PurpurWallBlock;
import net.mcreator.extrabuildingblocks.block.PurpleStainedSoulGlassPaneBlock;
import net.mcreator.extrabuildingblocks.block.PurpleStainedSoulGlassBlock;
import net.mcreator.extrabuildingblocks.block.PurpleLaceCarpetBlock;
import net.mcreator.extrabuildingblocks.block.PurpleLaceBannerBlock;
import net.mcreator.extrabuildingblocks.block.PurpleFountainGrassBlock;
import net.mcreator.extrabuildingblocks.block.PurpleDesertBushBlock;
import net.mcreator.extrabuildingblocks.block.PrismarinePillarBlock;
import net.mcreator.extrabuildingblocks.block.PrismarineBrickWallBlock;
import net.mcreator.extrabuildingblocks.block.PottedChorusBlock;
import net.mcreator.extrabuildingblocks.block.PolishedDripstoneWallBlock;
import net.mcreator.extrabuildingblocks.block.PolishedDripstoneStairsBlock;
import net.mcreator.extrabuildingblocks.block.PolishedDripstoneSlabBlock;
import net.mcreator.extrabuildingblocks.block.PolishedDripstoneBlock;
import net.mcreator.extrabuildingblocks.block.PolishedCalciteWallBlock;
import net.mcreator.extrabuildingblocks.block.PolishedCalciteStairsBlock;
import net.mcreator.extrabuildingblocks.block.PolishedCalciteSlabBlock;
import net.mcreator.extrabuildingblocks.block.PolishedCalciteBlock;
import net.mcreator.extrabuildingblocks.block.PinkStainedSoulGlassPaneBlock;
import net.mcreator.extrabuildingblocks.block.PinkStainedSoulGlassBlock;
import net.mcreator.extrabuildingblocks.block.PinkLaceCarpetBlock;
import net.mcreator.extrabuildingblocks.block.PinkLaceBannerBlock;
import net.mcreator.extrabuildingblocks.block.OxidisedCopperBarsBlock;
import net.mcreator.extrabuildingblocks.block.OrangeStainedSoulGlassPaneBlock;
import net.mcreator.extrabuildingblocks.block.OrangeStainedSoulGlassBlock;
import net.mcreator.extrabuildingblocks.block.OrangeLaceCarpetBlock;
import net.mcreator.extrabuildingblocks.block.OrangeLaceBannerBlock;
import net.mcreator.extrabuildingblocks.block.OakBeamBlock;
import net.mcreator.extrabuildingblocks.block.MossyBricksBlock;
import net.mcreator.extrabuildingblocks.block.MangroveBeamBlock;
import net.mcreator.extrabuildingblocks.block.MagentaStainedSoulGlassPaneBlock;
import net.mcreator.extrabuildingblocks.block.MagentaLaceCarpetBlock;
import net.mcreator.extrabuildingblocks.block.MagentaLaceBannerBlock;
import net.mcreator.extrabuildingblocks.block.LimeStainedSoulGlassPaneBlock;
import net.mcreator.extrabuildingblocks.block.LimeStainedSoulGlassBlock;
import net.mcreator.extrabuildingblocks.block.LimeLaceCarpetBlock;
import net.mcreator.extrabuildingblocks.block.LimeLaceBannerBlock;
import net.mcreator.extrabuildingblocks.block.LightGreyLaceCarpetBlock;
import net.mcreator.extrabuildingblocks.block.LightGreyLaceBannerBlock;
import net.mcreator.extrabuildingblocks.block.LightBlueStainedSoulGlassPaneBlock;
import net.mcreator.extrabuildingblocks.block.LightBlueStainedSoulGlassBlock;
import net.mcreator.extrabuildingblocks.block.LightBlueLaceCarpetBlock;
import net.mcreator.extrabuildingblocks.block.LightBlueLaceBannerBlock;
import net.mcreator.extrabuildingblocks.block.LampBlock;
import net.mcreator.extrabuildingblocks.block.LaceCarpetBlock;
import net.mcreator.extrabuildingblocks.block.LaceBannerBlock;
import net.mcreator.extrabuildingblocks.block.JungleBeamBlock;
import net.mcreator.extrabuildingblocks.block.IronGateBlock;
import net.mcreator.extrabuildingblocks.block.IcicleTipBlock;
import net.mcreator.extrabuildingblocks.block.IcicleMiddleBlock;
import net.mcreator.extrabuildingblocks.block.IcicleFrustumBlock;
import net.mcreator.extrabuildingblocks.block.IcicleBaseBlock;
import net.mcreator.extrabuildingblocks.block.IceBricksBlock;
import net.mcreator.extrabuildingblocks.block.IceBrickWallBlock;
import net.mcreator.extrabuildingblocks.block.IceBrickStairsBlock;
import net.mcreator.extrabuildingblocks.block.IceBrickSlabBlock;
import net.mcreator.extrabuildingblocks.block.HookBlock;
import net.mcreator.extrabuildingblocks.block.HangingTorchflowerBlock;
import net.mcreator.extrabuildingblocks.block.GreyStainedSoulGlassPaneBlock;
import net.mcreator.extrabuildingblocks.block.GreyStainedSoulGlassBlock;
import net.mcreator.extrabuildingblocks.block.GreyLaceCarpetBlock;
import net.mcreator.extrabuildingblocks.block.GreyLaceBannerBlock;
import net.mcreator.extrabuildingblocks.block.GreenStainedSoulGlassPaneBlock;
import net.mcreator.extrabuildingblocks.block.GreenLaceCarpetBlock;
import net.mcreator.extrabuildingblocks.block.GreenLaceBannerBlock;
import net.mcreator.extrabuildingblocks.block.GreenDesertBushBlock;
import net.mcreator.extrabuildingblocks.block.FrostedGlassBlock;
import net.mcreator.extrabuildingblocks.block.FountainGrassBlock;
import net.mcreator.extrabuildingblocks.block.ExposedWroughtIronBlock;
import net.mcreator.extrabuildingblocks.block.ExposedCopperBarsBlock;
import net.mcreator.extrabuildingblocks.block.EndStoneWallBlock;
import net.mcreator.extrabuildingblocks.block.EndStoneStairsBlock;
import net.mcreator.extrabuildingblocks.block.EndStoneSlabBlock;
import net.mcreator.extrabuildingblocks.block.EchoCrystalBlock;
import net.mcreator.extrabuildingblocks.block.DuckWeedBlock;
import net.mcreator.extrabuildingblocks.block.DripstoneWallBlock;
import net.mcreator.extrabuildingblocks.block.DripstoneStairsBlock;
import net.mcreator.extrabuildingblocks.block.DripstoneSlabBlock;
import net.mcreator.extrabuildingblocks.block.DripstoneBricksBlock;
import net.mcreator.extrabuildingblocks.block.DripstoneBrickWallBlock;
import net.mcreator.extrabuildingblocks.block.DripstoneBrickStairsBlock;
import net.mcreator.extrabuildingblocks.block.DripstoneBrickSlabBlock;
import net.mcreator.extrabuildingblocks.block.DestroyedStoneBricksBlock;
import net.mcreator.extrabuildingblocks.block.DestroyedBricksBlock;
import net.mcreator.extrabuildingblocks.block.DarkPrismarineWallBlock;
import net.mcreator.extrabuildingblocks.block.DarkPrismarinePillarBlock;
import net.mcreator.extrabuildingblocks.block.DarkOakBeamBlock;
import net.mcreator.extrabuildingblocks.block.DarkGreyStainedSoulGlassPaneBlock;
import net.mcreator.extrabuildingblocks.block.DarkGreyStainedSoulGlassBlock;
import net.mcreator.extrabuildingblocks.block.CyanStainedSoulGlassPaneBlock;
import net.mcreator.extrabuildingblocks.block.CyanStainedSoulGlassBlock;
import net.mcreator.extrabuildingblocks.block.CyanLaceCarpetBlock;
import net.mcreator.extrabuildingblocks.block.CyanLaceBannerBlock;
import net.mcreator.extrabuildingblocks.block.CutSmoothStoneStairsBlock;
import net.mcreator.extrabuildingblocks.block.CutSmoothStoneSlabBlock;
import net.mcreator.extrabuildingblocks.block.CutSmoothStoneBlock;
import net.mcreator.extrabuildingblocks.block.CutGraniteStairsBlock;
import net.mcreator.extrabuildingblocks.block.CutGraniteSlabBlock;
import net.mcreator.extrabuildingblocks.block.CutGraniteBlock;
import net.mcreator.extrabuildingblocks.block.CutDioriteStairsBlock;
import net.mcreator.extrabuildingblocks.block.CutDioriteSlabBlock;
import net.mcreator.extrabuildingblocks.block.CutDioriteBlock;
import net.mcreator.extrabuildingblocks.block.CutAndesiteStairsBlock;
import net.mcreator.extrabuildingblocks.block.CutAndesiteSlabBlock;
import net.mcreator.extrabuildingblocks.block.CutAndesiteBlock;
import net.mcreator.extrabuildingblocks.block.CutAmethystBlock;
import net.mcreator.extrabuildingblocks.block.CrimsonBeamBlock;
import net.mcreator.extrabuildingblocks.block.CrackedRedNetherBrickBlock;
import net.mcreator.extrabuildingblocks.block.CrackedQuartzBricksBlock;
import net.mcreator.extrabuildingblocks.block.CrackedMudBricksBlock;
import net.mcreator.extrabuildingblocks.block.CrackedEndBricksBlock;
import net.mcreator.extrabuildingblocks.block.CrackedDripstoneBricksBlock;
import net.mcreator.extrabuildingblocks.block.CrackedCalciteBricksBlock;
import net.mcreator.extrabuildingblocks.block.CrackedBricksBlock;
import net.mcreator.extrabuildingblocks.block.CopperBarsBlock;
import net.mcreator.extrabuildingblocks.block.ChorusTrapdoorBlock;
import net.mcreator.extrabuildingblocks.block.ChorusStairsBlock;
import net.mcreator.extrabuildingblocks.block.ChorusSlabBlock;
import net.mcreator.extrabuildingblocks.block.ChorusPressurePlateBlock;
import net.mcreator.extrabuildingblocks.block.ChorusPlanksBlock;
import net.mcreator.extrabuildingblocks.block.ChorusFenceGateBlock;
import net.mcreator.extrabuildingblocks.block.ChorusFenceBlock;
import net.mcreator.extrabuildingblocks.block.ChorusDoorBlock;
import net.mcreator.extrabuildingblocks.block.ChorusButtonBlock;
import net.mcreator.extrabuildingblocks.block.ChiseledStoneBlock;
import net.mcreator.extrabuildingblocks.block.ChiseledSoulSlateBlock;
import net.mcreator.extrabuildingblocks.block.ChiseledRedNetherBrickBlock;
import net.mcreator.extrabuildingblocks.block.ChiseledPrismarineBlock;
import net.mcreator.extrabuildingblocks.block.ChiseledEndStoneBricksBlock;
import net.mcreator.extrabuildingblocks.block.ChiseledDeepslateBricksBlock;
import net.mcreator.extrabuildingblocks.block.ChiseledBlackstoneBricksBlock;
import net.mcreator.extrabuildingblocks.block.CherryBeamBlock;
import net.mcreator.extrabuildingblocks.block.ChainMidBlock;
import net.mcreator.extrabuildingblocks.block.ChainLeftBlock;
import net.mcreator.extrabuildingblocks.block.ChainConnectedBlock;
import net.mcreator.extrabuildingblocks.block.CalciteWallBlock;
import net.mcreator.extrabuildingblocks.block.CalciteStairsBlock;
import net.mcreator.extrabuildingblocks.block.CalciteSlabBlock;
import net.mcreator.extrabuildingblocks.block.CalciteBricksBlock;
import net.mcreator.extrabuildingblocks.block.CalciteBrickWallBlock;
import net.mcreator.extrabuildingblocks.block.CalciteBrickStairsBlock;
import net.mcreator.extrabuildingblocks.block.CalciteBrickSlabBlock;
import net.mcreator.extrabuildingblocks.block.CactusWoodTrapdoorBlock;
import net.mcreator.extrabuildingblocks.block.CactusWoodDoorBlock;
import net.mcreator.extrabuildingblocks.block.CactusWoodBlock;
import net.mcreator.extrabuildingblocks.block.CactusWStairsBlock;
import net.mcreator.extrabuildingblocks.block.CactusWSlabBlock;
import net.mcreator.extrabuildingblocks.block.CactusWPressurePlateBlock;
import net.mcreator.extrabuildingblocks.block.CactusWPlanksBlock;
import net.mcreator.extrabuildingblocks.block.CactusWFenceGateBlock;
import net.mcreator.extrabuildingblocks.block.CactusWFenceBlock;
import net.mcreator.extrabuildingblocks.block.CactusWButtonBlock;
import net.mcreator.extrabuildingblocks.block.BusLaceCarpetBlock;
import net.mcreator.extrabuildingblocks.block.BrownStainedSoulGlassPaneBlock;
import net.mcreator.extrabuildingblocks.block.BrownStainedSoulGlassBlock;
import net.mcreator.extrabuildingblocks.block.BrownLaceCarpetBlock;
import net.mcreator.extrabuildingblocks.block.BrownLaceBannerBlock;
import net.mcreator.extrabuildingblocks.block.BracketBlock;
import net.mcreator.extrabuildingblocks.block.BraceBlock;
import net.mcreator.extrabuildingblocks.block.BlueStainedSoulGlassPaneBlock;
import net.mcreator.extrabuildingblocks.block.BlueStainedSoulGlassBlock;
import net.mcreator.extrabuildingblocks.block.BlueLaceCarpetBlock;
import net.mcreator.extrabuildingblocks.block.BlueLaceBannerBlock;
import net.mcreator.extrabuildingblocks.block.BlackStainedSoulGlassPaneBlock;
import net.mcreator.extrabuildingblocks.block.BlackStainedSoulGlassBlock;
import net.mcreator.extrabuildingblocks.block.BlackLaceCarpetBlock;
import net.mcreator.extrabuildingblocks.block.BlackLaceBannerBlock;
import net.mcreator.extrabuildingblocks.block.BirchBeamBlock;
import net.mcreator.extrabuildingblocks.block.BambooBeamBlock;
import net.mcreator.extrabuildingblocks.block.AcaciaBeamBlock;
import net.mcreator.extrabuildingblocks.ExtraBuildingBlocksMod;

public class ExtraBuildingBlocksModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, ExtraBuildingBlocksMod.MODID);
	public static final RegistryObject<Block> CUT_ANDESITE = REGISTRY.register("cut_andesite", () -> new CutAndesiteBlock());
	public static final RegistryObject<Block> CUT_ANDESITE_STAIRS = REGISTRY.register("cut_andesite_stairs", () -> new CutAndesiteStairsBlock());
	public static final RegistryObject<Block> CUT_ANDESITE_SLAB = REGISTRY.register("cut_andesite_slab", () -> new CutAndesiteSlabBlock());
	public static final RegistryObject<Block> CUT_GRANITE = REGISTRY.register("cut_granite", () -> new CutGraniteBlock());
	public static final RegistryObject<Block> CUT_GRANITE_STAIRS = REGISTRY.register("cut_granite_stairs", () -> new CutGraniteStairsBlock());
	public static final RegistryObject<Block> CUT_GRANITE_SLAB = REGISTRY.register("cut_granite_slab", () -> new CutGraniteSlabBlock());
	public static final RegistryObject<Block> SWAMPVINE = REGISTRY.register("swampvine", () -> new SwampvineBlock());
	public static final RegistryObject<Block> LAMP = REGISTRY.register("lamp", () -> new LampBlock());
	public static final RegistryObject<Block> TEST = REGISTRY.register("test", () -> new TESTBlock());
	public static final RegistryObject<Block> POLISHED_CALCITE = REGISTRY.register("polished_calcite", () -> new PolishedCalciteBlock());
	public static final RegistryObject<Block> POLISHED_CALCITE_STAIRS = REGISTRY.register("polished_calcite_stairs", () -> new PolishedCalciteStairsBlock());
	public static final RegistryObject<Block> POLISHED_CALCITE_SLAB = REGISTRY.register("polished_calcite_slab", () -> new PolishedCalciteSlabBlock());
	public static final RegistryObject<Block> POLISHED_CALCITE_WALL = REGISTRY.register("polished_calcite_wall", () -> new PolishedCalciteWallBlock());
	public static final RegistryObject<Block> CALCITE_STAIRS = REGISTRY.register("calcite_stairs", () -> new CalciteStairsBlock());
	public static final RegistryObject<Block> CALCITE_SLAB = REGISTRY.register("calcite_slab", () -> new CalciteSlabBlock());
	public static final RegistryObject<Block> CALCITE_BRICKS = REGISTRY.register("calcite_bricks", () -> new CalciteBricksBlock());
	public static final RegistryObject<Block> CALCITE_WALL = REGISTRY.register("calcite_wall", () -> new CalciteWallBlock());
	public static final RegistryObject<Block> CALCITE_BRICK_STAIRS = REGISTRY.register("calcite_brick_stairs", () -> new CalciteBrickStairsBlock());
	public static final RegistryObject<Block> CALCITE_BRICK_SLAB = REGISTRY.register("calcite_brick_slab", () -> new CalciteBrickSlabBlock());
	public static final RegistryObject<Block> CALCITE_BRICK_WALL = REGISTRY.register("calcite_brick_wall", () -> new CalciteBrickWallBlock());
	public static final RegistryObject<Block> CUT_DIORITE = REGISTRY.register("cut_diorite", () -> new CutDioriteBlock());
	public static final RegistryObject<Block> CUT_DIORITE_STAIRS = REGISTRY.register("cut_diorite_stairs", () -> new CutDioriteStairsBlock());
	public static final RegistryObject<Block> CUT_DIORITE_SLAB = REGISTRY.register("cut_diorite_slab", () -> new CutDioriteSlabBlock());
	public static final RegistryObject<Block> CRACKED_MUD_BRICKS = REGISTRY.register("cracked_mud_bricks", () -> new CrackedMudBricksBlock());
	public static final RegistryObject<Block> CRACKED_END_BRICKS = REGISTRY.register("cracked_end_bricks", () -> new CrackedEndBricksBlock());
	public static final RegistryObject<Block> CRACKED_QUARTZ_BRICKS = REGISTRY.register("cracked_quartz_bricks", () -> new CrackedQuartzBricksBlock());
	public static final RegistryObject<Block> QUARTZ_BRICK_STAIRS = REGISTRY.register("quartz_brick_stairs", () -> new QuartzBrickStairsBlock());
	public static final RegistryObject<Block> QUARTZ_BRICK_SLAB = REGISTRY.register("quartz_brick_slab", () -> new QuartzBrickSlabBlock());
	public static final RegistryObject<Block> QUARTZ_BRICK_WALL = REGISTRY.register("quartz_brick_wall", () -> new QuartzBrickWallBlock());
	public static final RegistryObject<Block> CRACKED_RED_NETHER_BRICK = REGISTRY.register("cracked_red_nether_brick", () -> new CrackedRedNetherBrickBlock());
	public static final RegistryObject<Block> BRACKET = REGISTRY.register("bracket", () -> new BracketBlock());
	public static final RegistryObject<Block> POLISHED_DRIPSTONE = REGISTRY.register("polished_dripstone", () -> new PolishedDripstoneBlock());
	public static final RegistryObject<Block> POLISHED_DRIPSTONE_STAIRS = REGISTRY.register("polished_dripstone_stairs", () -> new PolishedDripstoneStairsBlock());
	public static final RegistryObject<Block> POLISHED_DRIPSTONE_SLAB = REGISTRY.register("polished_dripstone_slab", () -> new PolishedDripstoneSlabBlock());
	public static final RegistryObject<Block> POLISHED_DRIPSTONE_WALL = REGISTRY.register("polished_dripstone_wall", () -> new PolishedDripstoneWallBlock());
	public static final RegistryObject<Block> DRIPSTONE_BRICKS = REGISTRY.register("dripstone_bricks", () -> new DripstoneBricksBlock());
	public static final RegistryObject<Block> DRIPSTONE_BRICK_STAIRS = REGISTRY.register("dripstone_brick_stairs", () -> new DripstoneBrickStairsBlock());
	public static final RegistryObject<Block> DRIPSTONE_BRICK_SLAB = REGISTRY.register("dripstone_brick_slab", () -> new DripstoneBrickSlabBlock());
	public static final RegistryObject<Block> DRIPSTONE_BRICK_WALL = REGISTRY.register("dripstone_brick_wall", () -> new DripstoneBrickWallBlock());
	public static final RegistryObject<Block> DRIPSTONE_STAIRS = REGISTRY.register("dripstone_stairs", () -> new DripstoneStairsBlock());
	public static final RegistryObject<Block> DRIPSTONE_SLAB = REGISTRY.register("dripstone_slab", () -> new DripstoneSlabBlock());
	public static final RegistryObject<Block> DRIPSTONE_WALL = REGISTRY.register("dripstone_wall", () -> new DripstoneWallBlock());
	public static final RegistryObject<Block> CRACKED_DRIPSTONE_BRICKS = REGISTRY.register("cracked_dripstone_bricks", () -> new CrackedDripstoneBricksBlock());
	public static final RegistryObject<Block> CRACKED_CALCITE_BRICKS = REGISTRY.register("cracked_calcite_bricks", () -> new CrackedCalciteBricksBlock());
	public static final RegistryObject<Block> CHAIN_LEFT = REGISTRY.register("chain_left", () -> new ChainLeftBlock());
	public static final RegistryObject<Block> CHAIN_MID = REGISTRY.register("chain_mid", () -> new ChainMidBlock());
	public static final RegistryObject<Block> CHAIN_CONNECTED = REGISTRY.register("chain_connected", () -> new ChainConnectedBlock());
	public static final RegistryObject<Block> ICE_BRICKS = REGISTRY.register("ice_bricks", () -> new IceBricksBlock());
	public static final RegistryObject<Block> ICE_BRICK_STAIRS = REGISTRY.register("ice_brick_stairs", () -> new IceBrickStairsBlock());
	public static final RegistryObject<Block> ICE_BRICK_SLAB = REGISTRY.register("ice_brick_slab", () -> new IceBrickSlabBlock());
	public static final RegistryObject<Block> ICE_BRICK_WALL = REGISTRY.register("ice_brick_wall", () -> new IceBrickWallBlock());
	public static final RegistryObject<Block> CUT_SMOOTH_STONE = REGISTRY.register("cut_smooth_stone", () -> new CutSmoothStoneBlock());
	public static final RegistryObject<Block> CUT_SMOOTH_STONE_STAIRS = REGISTRY.register("cut_smooth_stone_stairs", () -> new CutSmoothStoneStairsBlock());
	public static final RegistryObject<Block> CUT_SMOOTH_STONE_SLAB = REGISTRY.register("cut_smooth_stone_slab", () -> new CutSmoothStoneSlabBlock());
	public static final RegistryObject<Block> SMOOTH_STONE_WALL = REGISTRY.register("smooth_stone_wall", () -> new SmoothStoneWallBlock());
	public static final RegistryObject<Block> ICICLE_TIP = REGISTRY.register("icicle_tip", () -> new IcicleTipBlock());
	public static final RegistryObject<Block> ICICLE_FRUSTUM = REGISTRY.register("icicle_frustum", () -> new IcicleFrustumBlock());
	public static final RegistryObject<Block> ICICLE_MIDDLE = REGISTRY.register("icicle_middle", () -> new IcicleMiddleBlock());
	public static final RegistryObject<Block> ICICLE_BASE = REGISTRY.register("icicle_base", () -> new IcicleBaseBlock());
	public static final RegistryObject<Block> CHORUS_PLANKS = REGISTRY.register("chorus_planks", () -> new ChorusPlanksBlock());
	public static final RegistryObject<Block> CHORUS_STAIRS = REGISTRY.register("chorus_stairs", () -> new ChorusStairsBlock());
	public static final RegistryObject<Block> CHORUS_SLAB = REGISTRY.register("chorus_slab", () -> new ChorusSlabBlock());
	public static final RegistryObject<Block> CHORUS_FENCE = REGISTRY.register("chorus_fence", () -> new ChorusFenceBlock());
	public static final RegistryObject<Block> CHORUS_FENCE_GATE = REGISTRY.register("chorus_fence_gate", () -> new ChorusFenceGateBlock());
	public static final RegistryObject<Block> CHORUS_PRESSURE_PLATE = REGISTRY.register("chorus_pressure_plate", () -> new ChorusPressurePlateBlock());
	public static final RegistryObject<Block> CHORUS_BUTTON = REGISTRY.register("chorus_button", () -> new ChorusButtonBlock());
	public static final RegistryObject<Block> CHORUS_DOOR = REGISTRY.register("chorus_door", () -> new ChorusDoorBlock());
	public static final RegistryObject<Block> CHORUS_TRAPDOOR = REGISTRY.register("chorus_trapdoor", () -> new ChorusTrapdoorBlock());
	public static final RegistryObject<Block> SOUL_LAMP = REGISTRY.register("soul_lamp", () -> new SoulLampBlock());
	public static final RegistryObject<Block> SOUL_SCONCE = REGISTRY.register("soul_sconce", () -> new SoulSconceBlock());
	public static final RegistryObject<Block> OAK_BEAM = REGISTRY.register("oak_beam", () -> new OakBeamBlock());
	public static final RegistryObject<Block> SPRUCE_BEAM = REGISTRY.register("spruce_beam", () -> new SpruceBeamBlock());
	public static final RegistryObject<Block> BIRCH_BEAM = REGISTRY.register("birch_beam", () -> new BirchBeamBlock());
	public static final RegistryObject<Block> DARK_OAK_BEAM = REGISTRY.register("dark_oak_beam", () -> new DarkOakBeamBlock());
	public static final RegistryObject<Block> ACACIA_BEAM = REGISTRY.register("acacia_beam", () -> new AcaciaBeamBlock());
	public static final RegistryObject<Block> MANGROVE_BEAM = REGISTRY.register("mangrove_beam", () -> new MangroveBeamBlock());
	public static final RegistryObject<Block> CHERRY_BEAM = REGISTRY.register("cherry_beam", () -> new CherryBeamBlock());
	public static final RegistryObject<Block> JUNGLE_BEAM = REGISTRY.register("jungle_beam", () -> new JungleBeamBlock());
	public static final RegistryObject<Block> BAMBOO_BEAM = REGISTRY.register("bamboo_beam", () -> new BambooBeamBlock());
	public static final RegistryObject<Block> CRIMSON_BEAM = REGISTRY.register("crimson_beam", () -> new CrimsonBeamBlock());
	public static final RegistryObject<Block> WARPED_BEAM = REGISTRY.register("warped_beam", () -> new WarpedBeamBlock());
	public static final RegistryObject<Block> CUT_AMETHYST = REGISTRY.register("cut_amethyst", () -> new CutAmethystBlock());
	public static final RegistryObject<Block> END_STONE_STAIRS = REGISTRY.register("end_stone_stairs", () -> new EndStoneStairsBlock());
	public static final RegistryObject<Block> END_STONE_SLAB = REGISTRY.register("end_stone_slab", () -> new EndStoneSlabBlock());
	public static final RegistryObject<Block> END_STONE_WALL = REGISTRY.register("end_stone_wall", () -> new EndStoneWallBlock());
	public static final RegistryObject<Block> SOUL_GLASS = REGISTRY.register("soul_glass", () -> new SoulGlassBlock());
	public static final RegistryObject<Block> SOUL_GLASS_PANE = REGISTRY.register("soul_glass_pane", () -> new SoulGlassPaneBlock());
	public static final RegistryObject<Block> WHITE_STAINED_SOUL_GLASS = REGISTRY.register("white_stained_soul_glass", () -> new WhiteStainedSoulGlassBlock());
	public static final RegistryObject<Block> WHITE_STAINED_SOUL_GLASS_PANE = REGISTRY.register("white_stained_soul_glass_pane", () -> new WhiteStainedSoulGlassPaneBlock());
	public static final RegistryObject<Block> GREY_STAINED_SOUL_GLASS = REGISTRY.register("grey_stained_soul_glass", () -> new GreyStainedSoulGlassBlock());
	public static final RegistryObject<Block> GREY_STAINED_SOUL_GLASS_PANE = REGISTRY.register("grey_stained_soul_glass_pane", () -> new GreyStainedSoulGlassPaneBlock());
	public static final RegistryObject<Block> BLACK_STAINED_SOUL_GLASS = REGISTRY.register("black_stained_soul_glass", () -> new BlackStainedSoulGlassBlock());
	public static final RegistryObject<Block> BLACK_STAINED_SOUL_GLASS_PANE = REGISTRY.register("black_stained_soul_glass_pane", () -> new BlackStainedSoulGlassPaneBlock());
	public static final RegistryObject<Block> RED_STAINED_SOUL_GLASS = REGISTRY.register("red_stained_soul_glass", () -> new RedStainedSoulGlassBlock());
	public static final RegistryObject<Block> RED_STAINED_SOUL_GLASS_PANE = REGISTRY.register("red_stained_soul_glass_pane", () -> new RedStainedSoulGlassPaneBlock());
	public static final RegistryObject<Block> ORANGE_STAINED_SOUL_GLASS = REGISTRY.register("orange_stained_soul_glass", () -> new OrangeStainedSoulGlassBlock());
	public static final RegistryObject<Block> ORANGE_STAINED_SOUL_GLASS_PANE = REGISTRY.register("orange_stained_soul_glass_pane", () -> new OrangeStainedSoulGlassPaneBlock());
	public static final RegistryObject<Block> YELLOW_STAINED_SOUL_GLASS = REGISTRY.register("yellow_stained_soul_glass", () -> new YellowStainedSoulGlassBlock());
	public static final RegistryObject<Block> YELLOW_STAINED_SOUL_GLASS_PANE = REGISTRY.register("yellow_stained_soul_glass_pane", () -> new YellowStainedSoulGlassPaneBlock());
	public static final RegistryObject<Block> LIME_STAINED_SOUL_GLASS = REGISTRY.register("lime_stained_soul_glass", () -> new LimeStainedSoulGlassBlock());
	public static final RegistryObject<Block> LIME_STAINED_SOUL_GLASS_PANE = REGISTRY.register("lime_stained_soul_glass_pane", () -> new LimeStainedSoulGlassPaneBlock());
	public static final RegistryObject<Block> GREEN_STAINED_SOUL_GLASS_PANE = REGISTRY.register("green_stained_soul_glass_pane", () -> new GreenStainedSoulGlassPaneBlock());
	public static final RegistryObject<Block> CYAN_STAINED_SOUL_GLASS = REGISTRY.register("cyan_stained_soul_glass", () -> new CyanStainedSoulGlassBlock());
	public static final RegistryObject<Block> CYAN_STAINED_SOUL_GLASS_PANE = REGISTRY.register("cyan_stained_soul_glass_pane", () -> new CyanStainedSoulGlassPaneBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_STAINED_SOUL_GLASS = REGISTRY.register("light_blue_stained_soul_glass", () -> new LightBlueStainedSoulGlassBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_STAINED_SOUL_GLASS_PANE = REGISTRY.register("light_blue_stained_soul_glass_pane", () -> new LightBlueStainedSoulGlassPaneBlock());
	public static final RegistryObject<Block> BLUE_STAINED_SOUL_GLASS = REGISTRY.register("blue_stained_soul_glass", () -> new BlueStainedSoulGlassBlock());
	public static final RegistryObject<Block> BLUE_STAINED_SOUL_GLASS_PANE = REGISTRY.register("blue_stained_soul_glass_pane", () -> new BlueStainedSoulGlassPaneBlock());
	public static final RegistryObject<Block> PURPLE_STAINED_SOUL_GLASS = REGISTRY.register("purple_stained_soul_glass", () -> new PurpleStainedSoulGlassBlock());
	public static final RegistryObject<Block> PURPLE_STAINED_SOUL_GLASS_PANE = REGISTRY.register("purple_stained_soul_glass_pane", () -> new PurpleStainedSoulGlassPaneBlock());
	public static final RegistryObject<Block> MAGENTA_STAINED_SOUL_GLASS_PANE = REGISTRY.register("magenta_stained_soul_glass_pane", () -> new MagentaStainedSoulGlassPaneBlock());
	public static final RegistryObject<Block> PINK_STAINED_SOUL_GLASS = REGISTRY.register("pink_stained_soul_glass", () -> new PinkStainedSoulGlassBlock());
	public static final RegistryObject<Block> PINK_STAINED_SOUL_GLASS_PANE = REGISTRY.register("pink_stained_soul_glass_pane", () -> new PinkStainedSoulGlassPaneBlock());
	public static final RegistryObject<Block> DARK_GREY_STAINED_SOUL_GLASS = REGISTRY.register("dark_grey_stained_soul_glass", () -> new DarkGreyStainedSoulGlassBlock());
	public static final RegistryObject<Block> DARK_GREY_STAINED_SOUL_GLASS_PANE = REGISTRY.register("dark_grey_stained_soul_glass_pane", () -> new DarkGreyStainedSoulGlassPaneBlock());
	public static final RegistryObject<Block> BROWN_STAINED_SOUL_GLASS = REGISTRY.register("brown_stained_soul_glass", () -> new BrownStainedSoulGlassBlock());
	public static final RegistryObject<Block> BROWN_STAINED_SOUL_GLASS_PANE = REGISTRY.register("brown_stained_soul_glass_pane", () -> new BrownStainedSoulGlassPaneBlock());
	public static final RegistryObject<Block> SANDSTONE_BRICKS = REGISTRY.register("sandstone_bricks", () -> new SandstoneBricksBlock());
	public static final RegistryObject<Block> SANDSTONE_BRICK_STAIRS = REGISTRY.register("sandstone_brick_stairs", () -> new SandstoneBrickStairsBlock());
	public static final RegistryObject<Block> SANDSTONE_BRICK_SLAB = REGISTRY.register("sandstone_brick_slab", () -> new SandstoneBrickSlabBlock());
	public static final RegistryObject<Block> SANDSTONE_BRICK_WALL = REGISTRY.register("sandstone_brick_wall", () -> new SandstoneBrickWallBlock());
	public static final RegistryObject<Block> RED_SANDSTONE_BRICKS = REGISTRY.register("red_sandstone_bricks", () -> new RedSandstoneBricksBlock());
	public static final RegistryObject<Block> RED_SANDSTONE_BRICK_STAIRS = REGISTRY.register("red_sandstone_brick_stairs", () -> new RedSandstoneBrickStairsBlock());
	public static final RegistryObject<Block> RED_SANDSTONE_BRICK_SLAB = REGISTRY.register("red_sandstone_brick_slab", () -> new RedSandstoneBrickSlabBlock());
	public static final RegistryObject<Block> RED_SANDSTONE_BRICK_WALL = REGISTRY.register("red_sandstone_brick_wall", () -> new RedSandstoneBrickWallBlock());
	public static final RegistryObject<Block> SOUL_SLATE = REGISTRY.register("soul_slate", () -> new SoulSlateBlock());
	public static final RegistryObject<Block> SOUL_SLATE_BRICKS = REGISTRY.register("soul_slate_bricks", () -> new SoulSlateBricksBlock());
	public static final RegistryObject<Block> CHISELED_SOUL_SLATE = REGISTRY.register("chiseled_soul_slate", () -> new ChiseledSoulSlateBlock());
	public static final RegistryObject<Block> SOUL_SLATE_BRICK_STAIRS = REGISTRY.register("soul_slate_brick_stairs", () -> new SoulSlateBrickStairsBlock());
	public static final RegistryObject<Block> SOUL_SLATE_BRICK_SLAB = REGISTRY.register("soul_slate_brick_slab", () -> new SoulSlateBrickSlabBlock());
	public static final RegistryObject<Block> SOUL_SLATE_BRICK_WALL = REGISTRY.register("soul_slate_brick_wall", () -> new SoulSlateBrickWallBlock());
	public static final RegistryObject<Block> PURPUR_WALL = REGISTRY.register("purpur_wall", () -> new PurpurWallBlock());
	public static final RegistryObject<Block> ECHO_CRYSTAL = REGISTRY.register("echo_crystal", () -> new EchoCrystalBlock());
	public static final RegistryObject<Block> CHISELED_END_STONE_BRICKS = REGISTRY.register("chiseled_end_stone_bricks", () -> new ChiseledEndStoneBricksBlock());
	public static final RegistryObject<Block> HANGING_TORCHFLOWER = REGISTRY.register("hanging_torchflower", () -> new HangingTorchflowerBlock());
	public static final RegistryObject<Block> RAW_SALT = REGISTRY.register("raw_salt", () -> new RawSaltBlock());
	public static final RegistryObject<Block> SALT_CRYSTAL = REGISTRY.register("salt_crystal", () -> new SaltCrystalBlock());
	public static final RegistryObject<Block> SALT_GROWTH = REGISTRY.register("salt_growth", () -> new SaltGrowthBlock());
	public static final RegistryObject<Block> STONE_PILLAR = REGISTRY.register("stone_pillar", () -> new StonePillarBlock());
	public static final RegistryObject<Block> CHISELED_RED_NETHER_BRICK = REGISTRY.register("chiseled_red_nether_brick", () -> new ChiseledRedNetherBrickBlock());
	public static final RegistryObject<Block> CACTUS_WOOD = REGISTRY.register("cactus_wood", () -> new CactusWoodBlock());
	public static final RegistryObject<Block> CACTUS_W_PLANKS = REGISTRY.register("cactus_w_planks", () -> new CactusWPlanksBlock());
	public static final RegistryObject<Block> CACTUS_W_STAIRS = REGISTRY.register("cactus_w_stairs", () -> new CactusWStairsBlock());
	public static final RegistryObject<Block> CACTUS_W_SLAB = REGISTRY.register("cactus_w_slab", () -> new CactusWSlabBlock());
	public static final RegistryObject<Block> CACTUS_W_FENCE = REGISTRY.register("cactus_w_fence", () -> new CactusWFenceBlock());
	public static final RegistryObject<Block> CACTUS_W_FENCE_GATE = REGISTRY.register("cactus_w_fence_gate", () -> new CactusWFenceGateBlock());
	public static final RegistryObject<Block> CACTUS_W_PRESSURE_PLATE = REGISTRY.register("cactus_w_pressure_plate", () -> new CactusWPressurePlateBlock());
	public static final RegistryObject<Block> CACTUS_W_BUTTON = REGISTRY.register("cactus_w_button", () -> new CactusWButtonBlock());
	public static final RegistryObject<Block> POTTED_CHORUS = REGISTRY.register("potted_chorus", () -> new PottedChorusBlock());
	public static final RegistryObject<Block> VERY_CRACKED_STONE_BRICKS = REGISTRY.register("very_cracked_stone_bricks", () -> new VeryCrackedStoneBricksBlock());
	public static final RegistryObject<Block> DESTROYED_STONE_BRICKS = REGISTRY.register("destroyed_stone_bricks", () -> new DestroyedStoneBricksBlock());
	public static final RegistryObject<Block> CRACKED_BRICKS = REGISTRY.register("cracked_bricks", () -> new CrackedBricksBlock());
	public static final RegistryObject<Block> VERY_CRACKED_BRICKS = REGISTRY.register("very_cracked_bricks", () -> new VeryCrackedBricksBlock());
	public static final RegistryObject<Block> DESTROYED_BRICKS = REGISTRY.register("destroyed_bricks", () -> new DestroyedBricksBlock());
	public static final RegistryObject<Block> MOSSY_BRICKS = REGISTRY.register("mossy_bricks", () -> new MossyBricksBlock());
	public static final RegistryObject<Block> CACTUS_WOOD_DOOR = REGISTRY.register("cactus_wood_door", () -> new CactusWoodDoorBlock());
	public static final RegistryObject<Block> CACTUS_WOOD_TRAPDOOR = REGISTRY.register("cactus_wood_trapdoor", () -> new CactusWoodTrapdoorBlock());
	public static final RegistryObject<Block> LACE_BANNER = REGISTRY.register("lace_banner", () -> new LaceBannerBlock());
	public static final RegistryObject<Block> WHITE_LACE_BANNER = REGISTRY.register("white_lace_banner", () -> new WhiteLaceBannerBlock());
	public static final RegistryObject<Block> LIGHT_GREY_LACE_BANNER = REGISTRY.register("light_grey_lace_banner", () -> new LightGreyLaceBannerBlock());
	public static final RegistryObject<Block> GREY_LACE_BANNER = REGISTRY.register("grey_lace_banner", () -> new GreyLaceBannerBlock());
	public static final RegistryObject<Block> BLACK_LACE_BANNER = REGISTRY.register("black_lace_banner", () -> new BlackLaceBannerBlock());
	public static final RegistryObject<Block> RED_LACE_BANNER = REGISTRY.register("red_lace_banner", () -> new RedLaceBannerBlock());
	public static final RegistryObject<Block> ORANGE_LACE_BANNER = REGISTRY.register("orange_lace_banner", () -> new OrangeLaceBannerBlock());
	public static final RegistryObject<Block> YELLOW_LACE_BANNER = REGISTRY.register("yellow_lace_banner", () -> new YellowLaceBannerBlock());
	public static final RegistryObject<Block> LIME_LACE_BANNER = REGISTRY.register("lime_lace_banner", () -> new LimeLaceBannerBlock());
	public static final RegistryObject<Block> GREEN_LACE_BANNER = REGISTRY.register("green_lace_banner", () -> new GreenLaceBannerBlock());
	public static final RegistryObject<Block> CYAN_LACE_BANNER = REGISTRY.register("cyan_lace_banner", () -> new CyanLaceBannerBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_LACE_BANNER = REGISTRY.register("light_blue_lace_banner", () -> new LightBlueLaceBannerBlock());
	public static final RegistryObject<Block> BLUE_LACE_BANNER = REGISTRY.register("blue_lace_banner", () -> new BlueLaceBannerBlock());
	public static final RegistryObject<Block> PURPLE_LACE_BANNER = REGISTRY.register("purple_lace_banner", () -> new PurpleLaceBannerBlock());
	public static final RegistryObject<Block> MAGENTA_LACE_BANNER = REGISTRY.register("magenta_lace_banner", () -> new MagentaLaceBannerBlock());
	public static final RegistryObject<Block> PINK_LACE_BANNER = REGISTRY.register("pink_lace_banner", () -> new PinkLaceBannerBlock());
	public static final RegistryObject<Block> BROWN_LACE_BANNER = REGISTRY.register("brown_lace_banner", () -> new BrownLaceBannerBlock());
	public static final RegistryObject<Block> PRISMARINE_BRICK_WALL = REGISTRY.register("prismarine_brick_wall", () -> new PrismarineBrickWallBlock());
	public static final RegistryObject<Block> DARK_PRISMARINE_WALL = REGISTRY.register("dark_prismarine_wall", () -> new DarkPrismarineWallBlock());
	public static final RegistryObject<Block> PRISMARINE_PILLAR = REGISTRY.register("prismarine_pillar", () -> new PrismarinePillarBlock());
	public static final RegistryObject<Block> DARK_PRISMARINE_PILLAR = REGISTRY.register("dark_prismarine_pillar", () -> new DarkPrismarinePillarBlock());
	public static final RegistryObject<Block> CHISELED_PRISMARINE = REGISTRY.register("chiseled_prismarine", () -> new ChiseledPrismarineBlock());
	public static final RegistryObject<Block> SALT_CRYSTAL_EMISSIVE = REGISTRY.register("salt_crystal_emissive", () -> new SaltCrystalEmissiveBlock());
	public static final RegistryObject<Block> SOUL_MAGMA = REGISTRY.register("soul_magma", () -> new SoulMagmaBlock());
	public static final RegistryObject<Block> RED_LACE_CARPET = REGISTRY.register("red_lace_carpet", () -> new RedLaceCarpetBlock());
	public static final RegistryObject<Block> ORANGE_LACE_CARPET = REGISTRY.register("orange_lace_carpet", () -> new OrangeLaceCarpetBlock());
	public static final RegistryObject<Block> YELLOW_LACE_CARPET = REGISTRY.register("yellow_lace_carpet", () -> new YellowLaceCarpetBlock());
	public static final RegistryObject<Block> LIME_LACE_CARPET = REGISTRY.register("lime_lace_carpet", () -> new LimeLaceCarpetBlock());
	public static final RegistryObject<Block> GREEN_LACE_CARPET = REGISTRY.register("green_lace_carpet", () -> new GreenLaceCarpetBlock());
	public static final RegistryObject<Block> CYAN_LACE_CARPET = REGISTRY.register("cyan_lace_carpet", () -> new CyanLaceCarpetBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_LACE_CARPET = REGISTRY.register("light_blue_lace_carpet", () -> new LightBlueLaceCarpetBlock());
	public static final RegistryObject<Block> BLUE_LACE_CARPET = REGISTRY.register("blue_lace_carpet", () -> new BlueLaceCarpetBlock());
	public static final RegistryObject<Block> PURPLE_LACE_CARPET = REGISTRY.register("purple_lace_carpet", () -> new PurpleLaceCarpetBlock());
	public static final RegistryObject<Block> MAGENTA_LACE_CARPET = REGISTRY.register("magenta_lace_carpet", () -> new MagentaLaceCarpetBlock());
	public static final RegistryObject<Block> PINK_LACE_CARPET = REGISTRY.register("pink_lace_carpet", () -> new PinkLaceCarpetBlock());
	public static final RegistryObject<Block> BROWN_LACE_CARPET = REGISTRY.register("brown_lace_carpet", () -> new BrownLaceCarpetBlock());
	public static final RegistryObject<Block> BLACK_LACE_CARPET = REGISTRY.register("black_lace_carpet", () -> new BlackLaceCarpetBlock());
	public static final RegistryObject<Block> GREY_LACE_CARPET = REGISTRY.register("grey_lace_carpet", () -> new GreyLaceCarpetBlock());
	public static final RegistryObject<Block> LIGHT_GREY_LACE_CARPET = REGISTRY.register("light_grey_lace_carpet", () -> new LightGreyLaceCarpetBlock());
	public static final RegistryObject<Block> WHITE_LACE_CARPET = REGISTRY.register("white_lace_carpet", () -> new WhiteLaceCarpetBlock());
	public static final RegistryObject<Block> BUS_LACE_CARPET = REGISTRY.register("bus_lace_carpet", () -> new BusLaceCarpetBlock());
	public static final RegistryObject<Block> LACE_CARPET = REGISTRY.register("lace_carpet", () -> new LaceCarpetBlock());
	public static final RegistryObject<Block> CHISELED_STONE = REGISTRY.register("chiseled_stone", () -> new ChiseledStoneBlock());
	public static final RegistryObject<Block> CHISELED_DEEPSLATE_BRICKS = REGISTRY.register("chiseled_deepslate_bricks", () -> new ChiseledDeepslateBricksBlock());
	public static final RegistryObject<Block> CHISELED_BLACKSTONE_BRICKS = REGISTRY.register("chiseled_blackstone_bricks", () -> new ChiseledBlackstoneBricksBlock());
	public static final RegistryObject<Block> HOOK = REGISTRY.register("hook", () -> new HookBlock());
	public static final RegistryObject<Block> DUCK_WEED = REGISTRY.register("duck_weed", () -> new DuckWeedBlock());
	public static final RegistryObject<Block> FOUNTAIN_GRASS = REGISTRY.register("fountain_grass", () -> new FountainGrassBlock());
	public static final RegistryObject<Block> PURPLE_FOUNTAIN_GRASS = REGISTRY.register("purple_fountain_grass", () -> new PurpleFountainGrassBlock());
	public static final RegistryObject<Block> SWAMP_GRASS = REGISTRY.register("swamp_grass", () -> new SwampGrassBlock());
	public static final RegistryObject<Block> GREEN_DESERT_BUSH = REGISTRY.register("green_desert_bush", () -> new GreenDesertBushBlock());
	public static final RegistryObject<Block> PURPLE_DESERT_BUSH = REGISTRY.register("purple_desert_bush", () -> new PurpleDesertBushBlock());
	public static final RegistryObject<Block> BRACE = REGISTRY.register("brace", () -> new BraceBlock());
	public static final RegistryObject<Block> COPPER_BARS = REGISTRY.register("copper_bars", () -> new CopperBarsBlock());
	public static final RegistryObject<Block> EXPOSED_COPPER_BARS = REGISTRY.register("exposed_copper_bars", () -> new ExposedCopperBarsBlock());
	public static final RegistryObject<Block> WEATHERED_COPPER_BARS = REGISTRY.register("weathered_copper_bars", () -> new WeatheredCopperBarsBlock());
	public static final RegistryObject<Block> OXIDISED_COPPER_BARS = REGISTRY.register("oxidised_copper_bars", () -> new OxidisedCopperBarsBlock());
	public static final RegistryObject<Block> IRON_GATE = REGISTRY.register("iron_gate", () -> new IronGateBlock());
	public static final RegistryObject<Block> WEATHERED_WROUGHT_IRON = REGISTRY.register("weathered_wrought_iron", () -> new WeatheredWroughtIronBlock());
	public static final RegistryObject<Block> WROUGHT_IRON_BARS = REGISTRY.register("wrought_iron_bars", () -> new WroughtIronBarsBlock());
	public static final RegistryObject<Block> FROSTED_GLASS = REGISTRY.register("frosted_glass", () -> new FrostedGlassBlock());
	public static final RegistryObject<Block> RUSTED_WROUGHT_IRON = REGISTRY.register("rusted_wrought_iron", () -> new RustedWroughtIronBlock());
	public static final RegistryObject<Block> EXPOSED_WROUGHT_IRON = REGISTRY.register("exposed_wrought_iron", () -> new ExposedWroughtIronBlock());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
