/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.extrabuildingblocks.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.extrabuildingblocks.item.LaceItem;
import net.mcreator.extrabuildingblocks.block.*;
import net.mcreator.extrabuildingblocks.ExtraBuildingBlocksMod;

import java.util.function.Function;

public class ExtraBuildingBlocksModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(ExtraBuildingBlocksMod.MODID);
	public static final DeferredItem<Item> CUT_ANDESITE;
	public static final DeferredItem<Item> CUT_ANDESITE_STAIRS;
	public static final DeferredItem<Item> CUT_ANDESITE_SLAB;
	public static final DeferredItem<Item> CUT_GRANITE;
	public static final DeferredItem<Item> CUT_GRANITE_STAIRS;
	public static final DeferredItem<Item> CUT_GRANITE_SLAB;
	public static final DeferredItem<Item> SWAMPVINE;
	public static final DeferredItem<Item> STORM_LANTERN;
	public static final DeferredItem<Item> TEST;
	public static final DeferredItem<Item> POLISHED_CALCITE;
	public static final DeferredItem<Item> POLISHED_CALCITE_STAIRS;
	public static final DeferredItem<Item> POLISHED_CALCITE_SLAB;
	public static final DeferredItem<Item> POLISHED_CALCITE_WALL;
	public static final DeferredItem<Item> CALCITE_STAIRS;
	public static final DeferredItem<Item> CALCITE_SLAB;
	public static final DeferredItem<Item> CALCITE_BRICKS;
	public static final DeferredItem<Item> CALCITE_WALL;
	public static final DeferredItem<Item> CALCITE_BRICK_STAIRS;
	public static final DeferredItem<Item> CALCITE_BRICK_SLAB;
	public static final DeferredItem<Item> CALCITE_BRICK_WALL;
	public static final DeferredItem<Item> CUT_DIORITE;
	public static final DeferredItem<Item> CUT_DIORITE_STAIRS;
	public static final DeferredItem<Item> CUT_DIORITE_SLAB;
	public static final DeferredItem<Item> CRACKED_MUD_BRICKS;
	public static final DeferredItem<Item> CRACKED_END_BRICKS;
	public static final DeferredItem<Item> CRACKED_QUARTZ_BRICKS;
	public static final DeferredItem<Item> QUARTZ_BRICK_STAIRS;
	public static final DeferredItem<Item> QUARTZ_BRICK_SLAB;
	public static final DeferredItem<Item> QUARTZ_BRICK_WALL;
	public static final DeferredItem<Item> SMOOTH_STONE_STAIRS;
	public static final DeferredItem<Item> CRACKED_RED_NETHER_BRICK;
	public static final DeferredItem<Item> BRACKET;
	public static final DeferredItem<Item> SCONCE;
	public static final DeferredItem<Item> POLISHED_DRIPSTONE;
	public static final DeferredItem<Item> POLISHED_DRIPSTONE_STAIRS;
	public static final DeferredItem<Item> POLISHED_DRIPSTONE_SLAB;
	public static final DeferredItem<Item> POLISHED_DRIPSTONE_WALL;
	public static final DeferredItem<Item> DRIPSTONE_BRICKS;
	public static final DeferredItem<Item> DRIPSTONE_BRICK_STAIRS;
	public static final DeferredItem<Item> DRIPSTONE_BRICK_SLAB;
	public static final DeferredItem<Item> DRIPSTONE_BRICK_WALL;
	public static final DeferredItem<Item> DRIPSTONE_STAIRS;
	public static final DeferredItem<Item> DRIPSTONE_SLAB;
	public static final DeferredItem<Item> DRIPSTONE_WALL;
	public static final DeferredItem<Item> CRACKED_DRIPSTONE_BRICKS;
	public static final DeferredItem<Item> CRACKED_CALCITE_BRICKS;
	public static final DeferredItem<Item> CHAIN_LEFT;
	public static final DeferredItem<Item> CHAIN_MID;
	public static final DeferredItem<Item> CHAIN_CONNECTED;
	public static final DeferredItem<Item> ICE_BRICKS;
	public static final DeferredItem<Item> ICE_BRICK_STAIRS;
	public static final DeferredItem<Item> ICE_BRICK_SLAB;
	public static final DeferredItem<Item> ICE_BRICK_WALL;
	public static final DeferredItem<Item> CUT_SMOOTH_STONE;
	public static final DeferredItem<Item> CUT_SMOOTH_STONE_STAIRS;
	public static final DeferredItem<Item> CUT_SMOOTH_STONE_SLAB;
	public static final DeferredItem<Item> SMOOTH_STONE_WALL;
	public static final DeferredItem<Item> ICICLE;
	public static final DeferredItem<Item> CHORUS_PLANKS;
	public static final DeferredItem<Item> CHORUS_STAIRS;
	public static final DeferredItem<Item> CHORUS_SLAB;
	public static final DeferredItem<Item> CHORUS_FENCE;
	public static final DeferredItem<Item> CHORUS_FENCE_GATE;
	public static final DeferredItem<Item> CHORUS_PRESSURE_PLATE;
	public static final DeferredItem<Item> CHORUS_BUTTON;
	public static final DeferredItem<Item> CHORUS_DOOR;
	public static final DeferredItem<Item> CHORUS_TRAPDOOR;
	public static final DeferredItem<Item> SOUL_STORM_LANTERN;
	public static final DeferredItem<Item> SOUL_SCONCE;
	public static final DeferredItem<Item> OAK_BEAM;
	public static final DeferredItem<Item> SPRUCE_BEAM;
	public static final DeferredItem<Item> BIRCH_BEAM;
	public static final DeferredItem<Item> DARK_OAK_BEAM;
	public static final DeferredItem<Item> ACACIA_BEAM;
	public static final DeferredItem<Item> MANGROVE_BEAM;
	public static final DeferredItem<Item> CHERRY_BEAM;
	public static final DeferredItem<Item> JUNGLE_BEAM;
	public static final DeferredItem<Item> BAMBOO_BEAM;
	public static final DeferredItem<Item> CRIMSON_BEAM;
	public static final DeferredItem<Item> WARPED_BEAM;
	public static final DeferredItem<Item> CUT_AMETHYST;
	public static final DeferredItem<Item> END_STONE_STAIRS;
	public static final DeferredItem<Item> END_STONE_SLAB;
	public static final DeferredItem<Item> END_STONE_WALL;
	public static final DeferredItem<Item> SOUL_GLASS;
	public static final DeferredItem<Item> SOUL_GLASS_PANE;
	public static final DeferredItem<Item> WHITE_STAINED_SOUL_GLASS;
	public static final DeferredItem<Item> WHITE_STAINED_SOUL_GLASS_PANE;
	public static final DeferredItem<Item> GREY_STAINED_SOUL_GLASS;
	public static final DeferredItem<Item> GREY_STAINED_SOUL_GLASS_PANE;
	public static final DeferredItem<Item> BLACK_STAINED_SOUL_GLASS;
	public static final DeferredItem<Item> BLACK_STAINED_SOUL_GLASS_PANE;
	public static final DeferredItem<Item> RED_STAINED_SOUL_GLASS;
	public static final DeferredItem<Item> RED_STAINED_SOUL_GLASS_PANE;
	public static final DeferredItem<Item> ORANGE_STAINED_SOUL_GLASS;
	public static final DeferredItem<Item> ORANGE_STAINED_SOUL_GLASS_PANE;
	public static final DeferredItem<Item> YELLOW_STAINED_SOUL_GLASS;
	public static final DeferredItem<Item> YELLOW_STAINED_SOUL_GLASS_PANE;
	public static final DeferredItem<Item> LIME_STAINED_SOUL_GLASS;
	public static final DeferredItem<Item> LIME_STAINED_SOUL_GLASS_PANE;
	public static final DeferredItem<Item> GREEN_STAINED_SOUL_GLASS;
	public static final DeferredItem<Item> GREEN_STAINED_SOUL_GLASS_PANE;
	public static final DeferredItem<Item> CYAN_STAINED_SOUL_GLASS;
	public static final DeferredItem<Item> CYAN_STAINED_SOUL_GLASS_PANE;
	public static final DeferredItem<Item> LIGHT_BLUE_STAINED_SOUL_GLASS;
	public static final DeferredItem<Item> LIGHT_BLUE_STAINED_SOUL_GLASS_PANE;
	public static final DeferredItem<Item> BLUE_STAINED_SOUL_GLASS;
	public static final DeferredItem<Item> BLUE_STAINED_SOUL_GLASS_PANE;
	public static final DeferredItem<Item> PURPLE_STAINED_SOUL_GLASS;
	public static final DeferredItem<Item> PURPLE_STAINED_SOUL_GLASS_PANE;
	public static final DeferredItem<Item> MAGENTA_STAINED_SOUL_GLASS;
	public static final DeferredItem<Item> MAGENTA_STAINED_SOUL_GLASS_PANE;
	public static final DeferredItem<Item> PINK_STAINED_SOUL_GLASS;
	public static final DeferredItem<Item> PINK_STAINED_SOUL_GLASS_PANE;
	public static final DeferredItem<Item> DARK_GREY_STAINED_SOUL_GLASS;
	public static final DeferredItem<Item> DARK_GREY_STAINED_SOUL_GLASS_PANE;
	public static final DeferredItem<Item> BROWN_STAINED_SOUL_GLASS;
	public static final DeferredItem<Item> BROWN_STAINED_SOUL_GLASS_PANE;
	public static final DeferredItem<Item> SANDSTONE_BRICKS;
	public static final DeferredItem<Item> SANDSTONE_BRICK_STAIRS;
	public static final DeferredItem<Item> SANDSTONE_BRICK_SLAB;
	public static final DeferredItem<Item> SANDSTONE_BRICK_WALL;
	public static final DeferredItem<Item> RED_SANDSTONE_BRICKS;
	public static final DeferredItem<Item> RED_SANDSTONE_BRICK_STAIRS;
	public static final DeferredItem<Item> RED_SANDSTONE_BRICK_SLAB;
	public static final DeferredItem<Item> RED_SANDSTONE_BRICK_WALL;
	public static final DeferredItem<Item> SOUL_SLATE;
	public static final DeferredItem<Item> SOUL_SLATE_BRICKS;
	public static final DeferredItem<Item> CHISELED_SOUL_SLATE;
	public static final DeferredItem<Item> SOUL_SLATE_BRICK_STAIRS;
	public static final DeferredItem<Item> SOUL_SLATE_BRICK_SLAB;
	public static final DeferredItem<Item> SOUL_SLATE_BRICK_WALL;
	public static final DeferredItem<Item> PURPUR_WALL;
	public static final DeferredItem<Item> ECHO_CRYSTAL;
	public static final DeferredItem<Item> CHISELED_END_STONE_BRICKS;
	public static final DeferredItem<Item> HANGING_TORCHFLOWER;
	public static final DeferredItem<Item> RAW_SALT;
	public static final DeferredItem<Item> SALT_CRYSTAL;
	public static final DeferredItem<Item> SALT_GROWTH;
	public static final DeferredItem<Item> WROUGHT_IRON;
	public static final DeferredItem<Item> STONE_PILLAR;
	public static final DeferredItem<Item> CHISELED_RED_NETHER_BRICK;
	public static final DeferredItem<Item> CACTUS_WOOD;
	public static final DeferredItem<Item> CACTUS_WOOD_PLANKS;
	public static final DeferredItem<Item> CACTUS_WOOD_STAIRS;
	public static final DeferredItem<Item> CACTUS_WOOD_SLAB;
	public static final DeferredItem<Item> CACTUS_WOOD_FENCE;
	public static final DeferredItem<Item> CACTUS_WOOD_FENCE_GATE;
	public static final DeferredItem<Item> CACTUS_WOOD_PRESSURE_PLATE;
	public static final DeferredItem<Item> CACTUS_WOOD_BUTTON;
	public static final DeferredItem<Item> POTTED_CHORUS;
	public static final DeferredItem<Item> VERY_CRACKED_STONE_BRICKS;
	public static final DeferredItem<Item> DESTROYED_STONE_BRICKS;
	public static final DeferredItem<Item> CRACKED_BRICKS;
	public static final DeferredItem<Item> VERY_CRACKED_BRICKS;
	public static final DeferredItem<Item> DESTROYED_BRICKS;
	public static final DeferredItem<Item> MOSSY_BRICKS;
	public static final DeferredItem<Item> CACTUS_WOOD_DOOR;
	public static final DeferredItem<Item> CACTUS_WOOD_TRAPDOOR;
	public static final DeferredItem<Item> LACE_BANNER;
	public static final DeferredItem<Item> LACE;
	public static final DeferredItem<Item> WHITE_LACE_BANNER;
	public static final DeferredItem<Item> LIGHT_GREY_LACE_BANNER;
	public static final DeferredItem<Item> GREY_LACE_BANNER;
	public static final DeferredItem<Item> BLACK_LACE_BANNER;
	public static final DeferredItem<Item> RED_LACE_BANNER;
	public static final DeferredItem<Item> ORANGE_LACE_BANNER;
	public static final DeferredItem<Item> YELLOW_LACE_BANNER;
	public static final DeferredItem<Item> LIME_LACE_BANNER;
	public static final DeferredItem<Item> GREEN_LACE_BANNER;
	public static final DeferredItem<Item> CYAN_LACE_BANNER;
	public static final DeferredItem<Item> LIGHT_BLUE_LACE_BANNER;
	public static final DeferredItem<Item> BLUE_LACE_BANNER;
	public static final DeferredItem<Item> PURPLE_LACE_BANNER;
	public static final DeferredItem<Item> MAGENTA_LACE_BANNER;
	public static final DeferredItem<Item> PINK_LACE_BANNER;
	public static final DeferredItem<Item> BROWN_LACE_BANNER;
	public static final DeferredItem<Item> PRISMARINE_BRICK_WALL;
	public static final DeferredItem<Item> DARK_PRISMARINE_WALL;
	public static final DeferredItem<Item> PRISMARINE_PILLAR;
	public static final DeferredItem<Item> DARK_PRISMARINE_PILLAR;
	public static final DeferredItem<Item> CHISELED_PRISMARINE;
	public static final DeferredItem<Item> SOUL_MAGMA;
	public static final DeferredItem<Item> RED_LACE_CARPET;
	public static final DeferredItem<Item> ORANGE_LACE_CARPET;
	public static final DeferredItem<Item> YELLOW_LACE_CARPET;
	public static final DeferredItem<Item> LIME_LACE_CARPET;
	public static final DeferredItem<Item> GREEN_LACE_CARPET;
	public static final DeferredItem<Item> CYAN_LACE_CARPET;
	public static final DeferredItem<Item> LIGHT_BLUE_LACE_CARPET;
	public static final DeferredItem<Item> BLUE_LACE_CARPET;
	public static final DeferredItem<Item> PURPLE_LACE_CARPET;
	public static final DeferredItem<Item> MAGENTA_LACE_CARPET;
	public static final DeferredItem<Item> PINK_LACE_CARPET;
	public static final DeferredItem<Item> BROWN_LACE_CARPET;
	public static final DeferredItem<Item> BLACK_LACE_CARPET;
	public static final DeferredItem<Item> GREY_LACE_CARPET;
	public static final DeferredItem<Item> LIGHT_GREY_LACE_CARPET;
	public static final DeferredItem<Item> WHITE_LACE_CARPET;
	public static final DeferredItem<Item> TRAIN_LACE_CARPET;
	public static final DeferredItem<Item> LACE_CARPET;
	public static final DeferredItem<Item> CHISELED_STONE;
	public static final DeferredItem<Item> CHISELED_DEEPSLATE_BRICKS;
	public static final DeferredItem<Item> CHISELED_BLACKSTONE_BRICKS;
	public static final DeferredItem<Item> HOOK;
	public static final DeferredItem<Item> DUCK_WEED;
	public static final DeferredItem<Item> FOUNTAIN_GRASS;
	public static final DeferredItem<Item> PURPLE_FOUNTAIN_GRASS;
	public static final DeferredItem<Item> SWAMP_GRASS;
	public static final DeferredItem<Item> GREEN_DESERT_BUSH;
	public static final DeferredItem<Item> PURPLE_DESERT_BUSH;
	public static final DeferredItem<Item> BRACE;
	public static final DeferredItem<Item> COPPER_BARS;
	public static final DeferredItem<Item> EXPOSED_COPPER_BARS;
	public static final DeferredItem<Item> WEATHERED_COPPER_BARS;
	public static final DeferredItem<Item> OXIDISED_COPPER_BARS;
	public static final DeferredItem<Item> IRON_GATE;
	public static final DeferredItem<Item> WEATHERED_WROUGHT_IRON;
	public static final DeferredItem<Item> WROUGHT_IRON_BARS;
	public static final DeferredItem<Item> FROSTED_GLASS;
	public static final DeferredItem<Item> RUSTED_WROUGHT_IRON;
	public static final DeferredItem<Item> EXPOSED_WROUGHT_IRON;
	public static final DeferredItem<Item> STONE_WALL;
	public static final DeferredItem<Item> DARK_SEA_LANTERN;
	public static final DeferredItem<Item> WROUGHT_IRON_GATE;
	public static final DeferredItem<Item> WAXED_WROUGHT_IRON;
	public static final DeferredItem<Item> WAXED_WEATHERED_WROUGHT_IRON;
	public static final DeferredItem<Item> WAXED_EXPOSED_WROUGHT_IRON;
	public static final DeferredItem<Item> WAXED_RUSTED_WROUGHT_IRON;
	public static final DeferredItem<Item> WAXED_COPPER_BARS;
	public static final DeferredItem<Item> WAXED_EXPOSED_COPPER_BARS;
	public static final DeferredItem<Item> WAXED_WEATHERED_COPPER_BARS;
	public static final DeferredItem<Item> WAXED_OXIDISED_COPPER_BARS;
	public static final DeferredItem<Item> EXPOSED_WROUGHT_IRON_BARS;
	public static final DeferredItem<Item> WEATHERED_WROUGHT_IRON_BARS;
	public static final DeferredItem<Item> RUSTED_WROUGHT_IRON_BARS;
	public static final DeferredItem<Item> WAXED_WROUGHT_IRON_BARS;
	public static final DeferredItem<Item> WAXED_WEATHERED_WROUGHT_IRON_BARS;
	public static final DeferredItem<Item> WAXED_EXPOSED_WROUGHT_IRON_BARS;
	public static final DeferredItem<Item> WAXED_RUSTED_WROUGHT_IRON_BARS;
	public static final DeferredItem<Item> EXPOSED_WROUGHT_IRON_GATE;
	public static final DeferredItem<Item> WEATHERED_WROUGHT_IRON_GATE;
	public static final DeferredItem<Item> RUSTED_WROUGHT_IRON_GATE;
	public static final DeferredItem<Item> WAXED_WROUGHT_IRON_GATE;
	public static final DeferredItem<Item> WAXED_EXPOSED_WROUGHT_IRON_GATE;
	public static final DeferredItem<Item> WAXED_WEATHERED_WROUGHT_IRON_GATE;
	public static final DeferredItem<Item> WAXED_RUSTED_WROUGHT_IRON_GATE;
	static {
		CUT_ANDESITE = block(ExtraBuildingBlocksModBlocks.CUT_ANDESITE);
		CUT_ANDESITE_STAIRS = block(ExtraBuildingBlocksModBlocks.CUT_ANDESITE_STAIRS);
		CUT_ANDESITE_SLAB = block(ExtraBuildingBlocksModBlocks.CUT_ANDESITE_SLAB);
		CUT_GRANITE = block(ExtraBuildingBlocksModBlocks.CUT_GRANITE);
		CUT_GRANITE_STAIRS = block(ExtraBuildingBlocksModBlocks.CUT_GRANITE_STAIRS);
		CUT_GRANITE_SLAB = block(ExtraBuildingBlocksModBlocks.CUT_GRANITE_SLAB);
		SWAMPVINE = register("swampvine", SwampvineBlock.Item::new);
		STORM_LANTERN = block(ExtraBuildingBlocksModBlocks.STORM_LANTERN);
		TEST = block(ExtraBuildingBlocksModBlocks.TEST);
		POLISHED_CALCITE = block(ExtraBuildingBlocksModBlocks.POLISHED_CALCITE);
		POLISHED_CALCITE_STAIRS = block(ExtraBuildingBlocksModBlocks.POLISHED_CALCITE_STAIRS);
		POLISHED_CALCITE_SLAB = block(ExtraBuildingBlocksModBlocks.POLISHED_CALCITE_SLAB);
		POLISHED_CALCITE_WALL = block(ExtraBuildingBlocksModBlocks.POLISHED_CALCITE_WALL);
		CALCITE_STAIRS = block(ExtraBuildingBlocksModBlocks.CALCITE_STAIRS);
		CALCITE_SLAB = block(ExtraBuildingBlocksModBlocks.CALCITE_SLAB);
		CALCITE_BRICKS = block(ExtraBuildingBlocksModBlocks.CALCITE_BRICKS);
		CALCITE_WALL = block(ExtraBuildingBlocksModBlocks.CALCITE_WALL);
		CALCITE_BRICK_STAIRS = block(ExtraBuildingBlocksModBlocks.CALCITE_BRICK_STAIRS);
		CALCITE_BRICK_SLAB = block(ExtraBuildingBlocksModBlocks.CALCITE_BRICK_SLAB);
		CALCITE_BRICK_WALL = block(ExtraBuildingBlocksModBlocks.CALCITE_BRICK_WALL);
		CUT_DIORITE = block(ExtraBuildingBlocksModBlocks.CUT_DIORITE);
		CUT_DIORITE_STAIRS = block(ExtraBuildingBlocksModBlocks.CUT_DIORITE_STAIRS);
		CUT_DIORITE_SLAB = block(ExtraBuildingBlocksModBlocks.CUT_DIORITE_SLAB);
		CRACKED_MUD_BRICKS = block(ExtraBuildingBlocksModBlocks.CRACKED_MUD_BRICKS);
		CRACKED_END_BRICKS = block(ExtraBuildingBlocksModBlocks.CRACKED_END_BRICKS);
		CRACKED_QUARTZ_BRICKS = block(ExtraBuildingBlocksModBlocks.CRACKED_QUARTZ_BRICKS);
		QUARTZ_BRICK_STAIRS = block(ExtraBuildingBlocksModBlocks.QUARTZ_BRICK_STAIRS);
		QUARTZ_BRICK_SLAB = block(ExtraBuildingBlocksModBlocks.QUARTZ_BRICK_SLAB);
		QUARTZ_BRICK_WALL = block(ExtraBuildingBlocksModBlocks.QUARTZ_BRICK_WALL);
		SMOOTH_STONE_STAIRS = block(ExtraBuildingBlocksModBlocks.SMOOTH_STONE_STAIRS);
		CRACKED_RED_NETHER_BRICK = block(ExtraBuildingBlocksModBlocks.CRACKED_RED_NETHER_BRICK);
		BRACKET = block(ExtraBuildingBlocksModBlocks.BRACKET);
		SCONCE = block(ExtraBuildingBlocksModBlocks.SCONCE);
		POLISHED_DRIPSTONE = block(ExtraBuildingBlocksModBlocks.POLISHED_DRIPSTONE);
		POLISHED_DRIPSTONE_STAIRS = block(ExtraBuildingBlocksModBlocks.POLISHED_DRIPSTONE_STAIRS);
		POLISHED_DRIPSTONE_SLAB = block(ExtraBuildingBlocksModBlocks.POLISHED_DRIPSTONE_SLAB);
		POLISHED_DRIPSTONE_WALL = block(ExtraBuildingBlocksModBlocks.POLISHED_DRIPSTONE_WALL);
		DRIPSTONE_BRICKS = block(ExtraBuildingBlocksModBlocks.DRIPSTONE_BRICKS);
		DRIPSTONE_BRICK_STAIRS = block(ExtraBuildingBlocksModBlocks.DRIPSTONE_BRICK_STAIRS);
		DRIPSTONE_BRICK_SLAB = block(ExtraBuildingBlocksModBlocks.DRIPSTONE_BRICK_SLAB);
		DRIPSTONE_BRICK_WALL = block(ExtraBuildingBlocksModBlocks.DRIPSTONE_BRICK_WALL);
		DRIPSTONE_STAIRS = block(ExtraBuildingBlocksModBlocks.DRIPSTONE_STAIRS);
		DRIPSTONE_SLAB = block(ExtraBuildingBlocksModBlocks.DRIPSTONE_SLAB);
		DRIPSTONE_WALL = block(ExtraBuildingBlocksModBlocks.DRIPSTONE_WALL);
		CRACKED_DRIPSTONE_BRICKS = block(ExtraBuildingBlocksModBlocks.CRACKED_DRIPSTONE_BRICKS);
		CRACKED_CALCITE_BRICKS = block(ExtraBuildingBlocksModBlocks.CRACKED_CALCITE_BRICKS);
		CHAIN_LEFT = block(ExtraBuildingBlocksModBlocks.CHAIN_LEFT);
		CHAIN_MID = block(ExtraBuildingBlocksModBlocks.CHAIN_MID);
		CHAIN_CONNECTED = block(ExtraBuildingBlocksModBlocks.CHAIN_CONNECTED);
		ICE_BRICKS = block(ExtraBuildingBlocksModBlocks.ICE_BRICKS);
		ICE_BRICK_STAIRS = block(ExtraBuildingBlocksModBlocks.ICE_BRICK_STAIRS);
		ICE_BRICK_SLAB = block(ExtraBuildingBlocksModBlocks.ICE_BRICK_SLAB);
		ICE_BRICK_WALL = block(ExtraBuildingBlocksModBlocks.ICE_BRICK_WALL);
		CUT_SMOOTH_STONE = block(ExtraBuildingBlocksModBlocks.CUT_SMOOTH_STONE);
		CUT_SMOOTH_STONE_STAIRS = block(ExtraBuildingBlocksModBlocks.CUT_SMOOTH_STONE_STAIRS);
		CUT_SMOOTH_STONE_SLAB = block(ExtraBuildingBlocksModBlocks.CUT_SMOOTH_STONE_SLAB);
		SMOOTH_STONE_WALL = block(ExtraBuildingBlocksModBlocks.SMOOTH_STONE_WALL);
		ICICLE = block(ExtraBuildingBlocksModBlocks.ICICLE);
		CHORUS_PLANKS = block(ExtraBuildingBlocksModBlocks.CHORUS_PLANKS);
		CHORUS_STAIRS = block(ExtraBuildingBlocksModBlocks.CHORUS_STAIRS);
		CHORUS_SLAB = block(ExtraBuildingBlocksModBlocks.CHORUS_SLAB);
		CHORUS_FENCE = block(ExtraBuildingBlocksModBlocks.CHORUS_FENCE);
		CHORUS_FENCE_GATE = block(ExtraBuildingBlocksModBlocks.CHORUS_FENCE_GATE);
		CHORUS_PRESSURE_PLATE = block(ExtraBuildingBlocksModBlocks.CHORUS_PRESSURE_PLATE);
		CHORUS_BUTTON = block(ExtraBuildingBlocksModBlocks.CHORUS_BUTTON);
		CHORUS_DOOR = doubleBlock(ExtraBuildingBlocksModBlocks.CHORUS_DOOR);
		CHORUS_TRAPDOOR = block(ExtraBuildingBlocksModBlocks.CHORUS_TRAPDOOR);
		SOUL_STORM_LANTERN = block(ExtraBuildingBlocksModBlocks.SOUL_STORM_LANTERN);
		SOUL_SCONCE = block(ExtraBuildingBlocksModBlocks.SOUL_SCONCE);
		OAK_BEAM = block(ExtraBuildingBlocksModBlocks.OAK_BEAM);
		SPRUCE_BEAM = block(ExtraBuildingBlocksModBlocks.SPRUCE_BEAM);
		BIRCH_BEAM = block(ExtraBuildingBlocksModBlocks.BIRCH_BEAM);
		DARK_OAK_BEAM = block(ExtraBuildingBlocksModBlocks.DARK_OAK_BEAM);
		ACACIA_BEAM = block(ExtraBuildingBlocksModBlocks.ACACIA_BEAM);
		MANGROVE_BEAM = block(ExtraBuildingBlocksModBlocks.MANGROVE_BEAM);
		CHERRY_BEAM = block(ExtraBuildingBlocksModBlocks.CHERRY_BEAM);
		JUNGLE_BEAM = block(ExtraBuildingBlocksModBlocks.JUNGLE_BEAM);
		BAMBOO_BEAM = block(ExtraBuildingBlocksModBlocks.BAMBOO_BEAM);
		CRIMSON_BEAM = block(ExtraBuildingBlocksModBlocks.CRIMSON_BEAM);
		WARPED_BEAM = block(ExtraBuildingBlocksModBlocks.WARPED_BEAM);
		CUT_AMETHYST = block(ExtraBuildingBlocksModBlocks.CUT_AMETHYST);
		END_STONE_STAIRS = block(ExtraBuildingBlocksModBlocks.END_STONE_STAIRS);
		END_STONE_SLAB = block(ExtraBuildingBlocksModBlocks.END_STONE_SLAB);
		END_STONE_WALL = block(ExtraBuildingBlocksModBlocks.END_STONE_WALL);
		SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.SOUL_GLASS);
		SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.SOUL_GLASS_PANE);
		WHITE_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.WHITE_STAINED_SOUL_GLASS);
		WHITE_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.WHITE_STAINED_SOUL_GLASS_PANE);
		GREY_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.GREY_STAINED_SOUL_GLASS);
		GREY_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.GREY_STAINED_SOUL_GLASS_PANE);
		BLACK_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.BLACK_STAINED_SOUL_GLASS);
		BLACK_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.BLACK_STAINED_SOUL_GLASS_PANE);
		RED_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.RED_STAINED_SOUL_GLASS);
		RED_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.RED_STAINED_SOUL_GLASS_PANE);
		ORANGE_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.ORANGE_STAINED_SOUL_GLASS);
		ORANGE_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.ORANGE_STAINED_SOUL_GLASS_PANE);
		YELLOW_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.YELLOW_STAINED_SOUL_GLASS);
		YELLOW_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.YELLOW_STAINED_SOUL_GLASS_PANE);
		LIME_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.LIME_STAINED_SOUL_GLASS);
		LIME_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.LIME_STAINED_SOUL_GLASS_PANE);
		GREEN_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.GREEN_STAINED_SOUL_GLASS);
		GREEN_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.GREEN_STAINED_SOUL_GLASS_PANE);
		CYAN_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.CYAN_STAINED_SOUL_GLASS);
		CYAN_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.CYAN_STAINED_SOUL_GLASS_PANE);
		LIGHT_BLUE_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.LIGHT_BLUE_STAINED_SOUL_GLASS);
		LIGHT_BLUE_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.LIGHT_BLUE_STAINED_SOUL_GLASS_PANE);
		BLUE_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.BLUE_STAINED_SOUL_GLASS);
		BLUE_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.BLUE_STAINED_SOUL_GLASS_PANE);
		PURPLE_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.PURPLE_STAINED_SOUL_GLASS);
		PURPLE_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.PURPLE_STAINED_SOUL_GLASS_PANE);
		MAGENTA_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.MAGENTA_STAINED_SOUL_GLASS);
		MAGENTA_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.MAGENTA_STAINED_SOUL_GLASS_PANE);
		PINK_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.PINK_STAINED_SOUL_GLASS);
		PINK_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.PINK_STAINED_SOUL_GLASS_PANE);
		DARK_GREY_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.DARK_GREY_STAINED_SOUL_GLASS);
		DARK_GREY_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.DARK_GREY_STAINED_SOUL_GLASS_PANE);
		BROWN_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.BROWN_STAINED_SOUL_GLASS);
		BROWN_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.BROWN_STAINED_SOUL_GLASS_PANE);
		SANDSTONE_BRICKS = block(ExtraBuildingBlocksModBlocks.SANDSTONE_BRICKS);
		SANDSTONE_BRICK_STAIRS = block(ExtraBuildingBlocksModBlocks.SANDSTONE_BRICK_STAIRS);
		SANDSTONE_BRICK_SLAB = block(ExtraBuildingBlocksModBlocks.SANDSTONE_BRICK_SLAB);
		SANDSTONE_BRICK_WALL = block(ExtraBuildingBlocksModBlocks.SANDSTONE_BRICK_WALL);
		RED_SANDSTONE_BRICKS = block(ExtraBuildingBlocksModBlocks.RED_SANDSTONE_BRICKS);
		RED_SANDSTONE_BRICK_STAIRS = block(ExtraBuildingBlocksModBlocks.RED_SANDSTONE_BRICK_STAIRS);
		RED_SANDSTONE_BRICK_SLAB = block(ExtraBuildingBlocksModBlocks.RED_SANDSTONE_BRICK_SLAB);
		RED_SANDSTONE_BRICK_WALL = block(ExtraBuildingBlocksModBlocks.RED_SANDSTONE_BRICK_WALL);
		SOUL_SLATE = block(ExtraBuildingBlocksModBlocks.SOUL_SLATE);
		SOUL_SLATE_BRICKS = block(ExtraBuildingBlocksModBlocks.SOUL_SLATE_BRICKS);
		CHISELED_SOUL_SLATE = register("chiseled_soul_slate", ChiseledSoulSlateBlock.Item::new);
		SOUL_SLATE_BRICK_STAIRS = block(ExtraBuildingBlocksModBlocks.SOUL_SLATE_BRICK_STAIRS);
		SOUL_SLATE_BRICK_SLAB = block(ExtraBuildingBlocksModBlocks.SOUL_SLATE_BRICK_SLAB);
		SOUL_SLATE_BRICK_WALL = block(ExtraBuildingBlocksModBlocks.SOUL_SLATE_BRICK_WALL);
		PURPUR_WALL = block(ExtraBuildingBlocksModBlocks.PURPUR_WALL);
		ECHO_CRYSTAL = block(ExtraBuildingBlocksModBlocks.ECHO_CRYSTAL);
		CHISELED_END_STONE_BRICKS = block(ExtraBuildingBlocksModBlocks.CHISELED_END_STONE_BRICKS);
		HANGING_TORCHFLOWER = block(ExtraBuildingBlocksModBlocks.HANGING_TORCHFLOWER);
		RAW_SALT = block(ExtraBuildingBlocksModBlocks.RAW_SALT);
		SALT_CRYSTAL = block(ExtraBuildingBlocksModBlocks.SALT_CRYSTAL);
		SALT_GROWTH = block(ExtraBuildingBlocksModBlocks.SALT_GROWTH);
		WROUGHT_IRON = block(ExtraBuildingBlocksModBlocks.WROUGHT_IRON);
		STONE_PILLAR = block(ExtraBuildingBlocksModBlocks.STONE_PILLAR);
		CHISELED_RED_NETHER_BRICK = block(ExtraBuildingBlocksModBlocks.CHISELED_RED_NETHER_BRICK);
		CACTUS_WOOD = block(ExtraBuildingBlocksModBlocks.CACTUS_WOOD);
		CACTUS_WOOD_PLANKS = block(ExtraBuildingBlocksModBlocks.CACTUS_WOOD_PLANKS);
		CACTUS_WOOD_STAIRS = block(ExtraBuildingBlocksModBlocks.CACTUS_WOOD_STAIRS);
		CACTUS_WOOD_SLAB = block(ExtraBuildingBlocksModBlocks.CACTUS_WOOD_SLAB);
		CACTUS_WOOD_FENCE = block(ExtraBuildingBlocksModBlocks.CACTUS_WOOD_FENCE);
		CACTUS_WOOD_FENCE_GATE = block(ExtraBuildingBlocksModBlocks.CACTUS_WOOD_FENCE_GATE);
		CACTUS_WOOD_PRESSURE_PLATE = block(ExtraBuildingBlocksModBlocks.CACTUS_WOOD_PRESSURE_PLATE);
		CACTUS_WOOD_BUTTON = block(ExtraBuildingBlocksModBlocks.CACTUS_WOOD_BUTTON);
		POTTED_CHORUS = block(ExtraBuildingBlocksModBlocks.POTTED_CHORUS);
		VERY_CRACKED_STONE_BRICKS = block(ExtraBuildingBlocksModBlocks.VERY_CRACKED_STONE_BRICKS);
		DESTROYED_STONE_BRICKS = block(ExtraBuildingBlocksModBlocks.DESTROYED_STONE_BRICKS);
		CRACKED_BRICKS = block(ExtraBuildingBlocksModBlocks.CRACKED_BRICKS);
		VERY_CRACKED_BRICKS = block(ExtraBuildingBlocksModBlocks.VERY_CRACKED_BRICKS);
		DESTROYED_BRICKS = block(ExtraBuildingBlocksModBlocks.DESTROYED_BRICKS);
		MOSSY_BRICKS = block(ExtraBuildingBlocksModBlocks.MOSSY_BRICKS);
		CACTUS_WOOD_DOOR = doubleBlock(ExtraBuildingBlocksModBlocks.CACTUS_WOOD_DOOR);
		CACTUS_WOOD_TRAPDOOR = block(ExtraBuildingBlocksModBlocks.CACTUS_WOOD_TRAPDOOR);
		LACE_BANNER = block(ExtraBuildingBlocksModBlocks.LACE_BANNER);
		LACE = register("lace", LaceItem::new);
		WHITE_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.WHITE_LACE_BANNER);
		LIGHT_GREY_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.LIGHT_GREY_LACE_BANNER);
		GREY_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.GREY_LACE_BANNER);
		BLACK_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.BLACK_LACE_BANNER);
		RED_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.RED_LACE_BANNER);
		ORANGE_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.ORANGE_LACE_BANNER);
		YELLOW_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.YELLOW_LACE_BANNER);
		LIME_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.LIME_LACE_BANNER);
		GREEN_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.GREEN_LACE_BANNER);
		CYAN_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.CYAN_LACE_BANNER);
		LIGHT_BLUE_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.LIGHT_BLUE_LACE_BANNER);
		BLUE_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.BLUE_LACE_BANNER);
		PURPLE_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.PURPLE_LACE_BANNER);
		MAGENTA_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.MAGENTA_LACE_BANNER);
		PINK_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.PINK_LACE_BANNER);
		BROWN_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.BROWN_LACE_BANNER);
		PRISMARINE_BRICK_WALL = block(ExtraBuildingBlocksModBlocks.PRISMARINE_BRICK_WALL);
		DARK_PRISMARINE_WALL = block(ExtraBuildingBlocksModBlocks.DARK_PRISMARINE_WALL);
		PRISMARINE_PILLAR = register("prismarine_pillar", PrismarinePillarBlock.Item::new);
		DARK_PRISMARINE_PILLAR = register("dark_prismarine_pillar", DarkPrismarinePillarBlock.Item::new);
		CHISELED_PRISMARINE = block(ExtraBuildingBlocksModBlocks.CHISELED_PRISMARINE);
		SOUL_MAGMA = block(ExtraBuildingBlocksModBlocks.SOUL_MAGMA);
		RED_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.RED_LACE_CARPET);
		ORANGE_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.ORANGE_LACE_CARPET);
		YELLOW_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.YELLOW_LACE_CARPET);
		LIME_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.LIME_LACE_CARPET);
		GREEN_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.GREEN_LACE_CARPET);
		CYAN_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.CYAN_LACE_CARPET);
		LIGHT_BLUE_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.LIGHT_BLUE_LACE_CARPET);
		BLUE_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.BLUE_LACE_CARPET);
		PURPLE_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.PURPLE_LACE_CARPET);
		MAGENTA_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.MAGENTA_LACE_CARPET);
		PINK_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.PINK_LACE_CARPET);
		BROWN_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.BROWN_LACE_CARPET);
		BLACK_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.BLACK_LACE_CARPET);
		GREY_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.GREY_LACE_CARPET);
		LIGHT_GREY_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.LIGHT_GREY_LACE_CARPET);
		WHITE_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.WHITE_LACE_CARPET);
		TRAIN_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.TRAIN_LACE_CARPET);
		LACE_CARPET = block(ExtraBuildingBlocksModBlocks.LACE_CARPET);
		CHISELED_STONE = register("chiseled_stone", ChiseledStoneBlock.Item::new);
		CHISELED_DEEPSLATE_BRICKS = register("chiseled_deepslate_bricks", ChiseledDeepslateBricksBlock.Item::new);
		CHISELED_BLACKSTONE_BRICKS = register("chiseled_blackstone_bricks", ChiseledBlackstoneBricksBlock.Item::new);
		HOOK = register("hook", HookBlock.Item::new);
		DUCK_WEED = block(ExtraBuildingBlocksModBlocks.DUCK_WEED);
		FOUNTAIN_GRASS = block(ExtraBuildingBlocksModBlocks.FOUNTAIN_GRASS);
		PURPLE_FOUNTAIN_GRASS = block(ExtraBuildingBlocksModBlocks.PURPLE_FOUNTAIN_GRASS);
		SWAMP_GRASS = register("swamp_grass", SwampGrassBlock.Item::new);
		GREEN_DESERT_BUSH = block(ExtraBuildingBlocksModBlocks.GREEN_DESERT_BUSH);
		PURPLE_DESERT_BUSH = block(ExtraBuildingBlocksModBlocks.PURPLE_DESERT_BUSH);
		BRACE = register("brace", BraceBlock.Item::new);
		COPPER_BARS = block(ExtraBuildingBlocksModBlocks.COPPER_BARS);
		EXPOSED_COPPER_BARS = block(ExtraBuildingBlocksModBlocks.EXPOSED_COPPER_BARS);
		WEATHERED_COPPER_BARS = block(ExtraBuildingBlocksModBlocks.WEATHERED_COPPER_BARS);
		OXIDISED_COPPER_BARS = block(ExtraBuildingBlocksModBlocks.OXIDISED_COPPER_BARS);
		IRON_GATE = register("iron_gate", IronGateBlock.Item::new);
		WEATHERED_WROUGHT_IRON = block(ExtraBuildingBlocksModBlocks.WEATHERED_WROUGHT_IRON);
		WROUGHT_IRON_BARS = block(ExtraBuildingBlocksModBlocks.WROUGHT_IRON_BARS);
		FROSTED_GLASS = block(ExtraBuildingBlocksModBlocks.FROSTED_GLASS);
		RUSTED_WROUGHT_IRON = block(ExtraBuildingBlocksModBlocks.RUSTED_WROUGHT_IRON);
		EXPOSED_WROUGHT_IRON = block(ExtraBuildingBlocksModBlocks.EXPOSED_WROUGHT_IRON);
		STONE_WALL = block(ExtraBuildingBlocksModBlocks.STONE_WALL);
		DARK_SEA_LANTERN = block(ExtraBuildingBlocksModBlocks.DARK_SEA_LANTERN);
		WROUGHT_IRON_GATE = block(ExtraBuildingBlocksModBlocks.WROUGHT_IRON_GATE);
		WAXED_WROUGHT_IRON = block(ExtraBuildingBlocksModBlocks.WAXED_WROUGHT_IRON);
		WAXED_WEATHERED_WROUGHT_IRON = block(ExtraBuildingBlocksModBlocks.WAXED_WEATHERED_WROUGHT_IRON);
		WAXED_EXPOSED_WROUGHT_IRON = block(ExtraBuildingBlocksModBlocks.WAXED_EXPOSED_WROUGHT_IRON);
		WAXED_RUSTED_WROUGHT_IRON = block(ExtraBuildingBlocksModBlocks.WAXED_RUSTED_WROUGHT_IRON);
		WAXED_COPPER_BARS = block(ExtraBuildingBlocksModBlocks.WAXED_COPPER_BARS);
		WAXED_EXPOSED_COPPER_BARS = block(ExtraBuildingBlocksModBlocks.WAXED_EXPOSED_COPPER_BARS);
		WAXED_WEATHERED_COPPER_BARS = block(ExtraBuildingBlocksModBlocks.WAXED_WEATHERED_COPPER_BARS);
		WAXED_OXIDISED_COPPER_BARS = block(ExtraBuildingBlocksModBlocks.WAXED_OXIDISED_COPPER_BARS);
		EXPOSED_WROUGHT_IRON_BARS = block(ExtraBuildingBlocksModBlocks.EXPOSED_WROUGHT_IRON_BARS);
		WEATHERED_WROUGHT_IRON_BARS = block(ExtraBuildingBlocksModBlocks.WEATHERED_WROUGHT_IRON_BARS);
		RUSTED_WROUGHT_IRON_BARS = block(ExtraBuildingBlocksModBlocks.RUSTED_WROUGHT_IRON_BARS);
		WAXED_WROUGHT_IRON_BARS = block(ExtraBuildingBlocksModBlocks.WAXED_WROUGHT_IRON_BARS);
		WAXED_WEATHERED_WROUGHT_IRON_BARS = block(ExtraBuildingBlocksModBlocks.WAXED_WEATHERED_WROUGHT_IRON_BARS);
		WAXED_EXPOSED_WROUGHT_IRON_BARS = block(ExtraBuildingBlocksModBlocks.WAXED_EXPOSED_WROUGHT_IRON_BARS);
		WAXED_RUSTED_WROUGHT_IRON_BARS = block(ExtraBuildingBlocksModBlocks.WAXED_RUSTED_WROUGHT_IRON_BARS);
		EXPOSED_WROUGHT_IRON_GATE = block(ExtraBuildingBlocksModBlocks.EXPOSED_WROUGHT_IRON_GATE);
		WEATHERED_WROUGHT_IRON_GATE = block(ExtraBuildingBlocksModBlocks.WEATHERED_WROUGHT_IRON_GATE);
		RUSTED_WROUGHT_IRON_GATE = block(ExtraBuildingBlocksModBlocks.RUSTED_WROUGHT_IRON_GATE);
		WAXED_WROUGHT_IRON_GATE = block(ExtraBuildingBlocksModBlocks.WAXED_WROUGHT_IRON_GATE);
		WAXED_EXPOSED_WROUGHT_IRON_GATE = block(ExtraBuildingBlocksModBlocks.WAXED_EXPOSED_WROUGHT_IRON_GATE);
		WAXED_WEATHERED_WROUGHT_IRON_GATE = block(ExtraBuildingBlocksModBlocks.WAXED_WEATHERED_WROUGHT_IRON_GATE);
		WAXED_RUSTED_WROUGHT_IRON_GATE = block(ExtraBuildingBlocksModBlocks.WAXED_RUSTED_WROUGHT_IRON_GATE);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new BlockItem(block.get(), prop), properties);
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return doubleBlock(block, new Item.Properties());
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new DoubleHighBlockItem(block.get(), prop), properties);
	}
}