/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.extrabuildingblocks.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.Block;

import net.mcreator.extrabuildingblocks.block.*;
import net.mcreator.extrabuildingblocks.ExtraBuildingBlocksMod;

import java.util.function.Function;

public class ExtraBuildingBlocksModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(ExtraBuildingBlocksMod.MODID);
	public static final DeferredBlock<Block> CUT_ANDESITE;
	public static final DeferredBlock<Block> CUT_ANDESITE_STAIRS;
	public static final DeferredBlock<Block> CUT_ANDESITE_SLAB;
	public static final DeferredBlock<Block> CUT_GRANITE;
	public static final DeferredBlock<Block> CUT_GRANITE_STAIRS;
	public static final DeferredBlock<Block> CUT_GRANITE_SLAB;
	public static final DeferredBlock<Block> SWAMPVINE;
	public static final DeferredBlock<Block> LAMP;
	public static final DeferredBlock<Block> TEST;
	public static final DeferredBlock<Block> POLISHED_CALCITE;
	public static final DeferredBlock<Block> POLISHED_CALCITE_STAIRS;
	public static final DeferredBlock<Block> POLISHED_CALCITE_SLAB;
	public static final DeferredBlock<Block> POLISHED_CALCITE_WALL;
	public static final DeferredBlock<Block> CALCITE_STAIRS;
	public static final DeferredBlock<Block> CALCITE_SLAB;
	public static final DeferredBlock<Block> CALCITE_BRICKS;
	public static final DeferredBlock<Block> CALCITE_WALL;
	public static final DeferredBlock<Block> CALCITE_BRICK_STAIRS;
	public static final DeferredBlock<Block> CALCITE_BRICK_SLAB;
	public static final DeferredBlock<Block> CALCITE_BRICK_WALL;
	public static final DeferredBlock<Block> CUT_DIORITE;
	public static final DeferredBlock<Block> CUT_DIORITE_STAIRS;
	public static final DeferredBlock<Block> CUT_DIORITE_SLAB;
	public static final DeferredBlock<Block> CRACKED_MUD_BRICKS;
	public static final DeferredBlock<Block> CRACKED_END_BRICKS;
	public static final DeferredBlock<Block> CRACKED_QUARTZ_BRICKS;
	public static final DeferredBlock<Block> QUARTZ_BRICK_STAIRS;
	public static final DeferredBlock<Block> QUARTZ_BRICK_SLAB;
	public static final DeferredBlock<Block> QUARTZ_BRICK_WALL;
	public static final DeferredBlock<Block> SMOOTH_STONE_STAIRS;
	public static final DeferredBlock<Block> CRACKED_RED_NETHER_BRICK;
	public static final DeferredBlock<Block> BRACKET;
	public static final DeferredBlock<Block> SCONCE;
	public static final DeferredBlock<Block> POLISHED_DRIPSTONE;
	public static final DeferredBlock<Block> POLISHED_DRIPSTONE_STAIRS;
	public static final DeferredBlock<Block> POLISHED_DRIPSTONE_SLAB;
	public static final DeferredBlock<Block> POLISHED_DRIPSTONE_WALL;
	public static final DeferredBlock<Block> DRIPSTONE_BRICKS;
	public static final DeferredBlock<Block> DRIPSTONE_BRICK_STAIRS;
	public static final DeferredBlock<Block> DRIPSTONE_BRICK_SLAB;
	public static final DeferredBlock<Block> DRIPSTONE_BRICK_WALL;
	public static final DeferredBlock<Block> DRIPSTONE_STAIRS;
	public static final DeferredBlock<Block> DRIPSTONE_SLAB;
	public static final DeferredBlock<Block> DRIPSTONE_WALL;
	public static final DeferredBlock<Block> CRACKED_DRIPSTONE_BRICKS;
	public static final DeferredBlock<Block> CRACKED_CALCITE_BRICKS;
	public static final DeferredBlock<Block> CHAIN_LEFT;
	public static final DeferredBlock<Block> CHAIN_MID;
	public static final DeferredBlock<Block> CHAIN_CONNECTED;
	public static final DeferredBlock<Block> ICE_BRICKS;
	public static final DeferredBlock<Block> ICE_BRICK_STAIRS;
	public static final DeferredBlock<Block> ICE_BRICK_SLAB;
	public static final DeferredBlock<Block> ICE_BRICK_WALL;
	public static final DeferredBlock<Block> CUT_SMOOTH_STONE;
	public static final DeferredBlock<Block> CUT_SMOOTH_STONE_STAIRS;
	public static final DeferredBlock<Block> CUT_SMOOTH_STONE_SLAB;
	public static final DeferredBlock<Block> SMOOTH_STONE_WALL;
	public static final DeferredBlock<Block> ICICLE_TIP;
	public static final DeferredBlock<Block> ICICLE_FRUSTUM;
	public static final DeferredBlock<Block> ICICLE_MIDDLE;
	public static final DeferredBlock<Block> ICICLE_BASE;
	public static final DeferredBlock<Block> CHORUS_PLANKS;
	public static final DeferredBlock<Block> CHORUS_STAIRS;
	public static final DeferredBlock<Block> CHORUS_SLAB;
	public static final DeferredBlock<Block> CHORUS_FENCE;
	public static final DeferredBlock<Block> CHORUS_FENCE_GATE;
	public static final DeferredBlock<Block> CHORUS_PRESSURE_PLATE;
	public static final DeferredBlock<Block> CHORUS_BUTTON;
	public static final DeferredBlock<Block> CHORUS_DOOR;
	public static final DeferredBlock<Block> CHORUS_TRAPDOOR;
	public static final DeferredBlock<Block> SOUL_LAMP;
	public static final DeferredBlock<Block> SOUL_SCONCE;
	public static final DeferredBlock<Block> OAK_BEAM;
	public static final DeferredBlock<Block> SPRUCE_BEAM;
	public static final DeferredBlock<Block> BIRCH_BEAM;
	public static final DeferredBlock<Block> DARK_OAK_BEAM;
	public static final DeferredBlock<Block> ACACIA_BEAM;
	public static final DeferredBlock<Block> MANGROVE_BEAM;
	public static final DeferredBlock<Block> CHERRY_BEAM;
	public static final DeferredBlock<Block> JUNGLE_BEAM;
	public static final DeferredBlock<Block> BAMBOO_BEAM;
	public static final DeferredBlock<Block> CRIMSON_BEAM;
	public static final DeferredBlock<Block> WARPED_BEAM;
	public static final DeferredBlock<Block> CUT_AMETHYST;
	public static final DeferredBlock<Block> END_STONE_STAIRS;
	public static final DeferredBlock<Block> END_STONE_SLAB;
	public static final DeferredBlock<Block> END_STONE_WALL;
	public static final DeferredBlock<Block> SOUL_GLASS;
	public static final DeferredBlock<Block> SOUL_GLASS_PANE;
	public static final DeferredBlock<Block> WHITE_STAINED_SOUL_GLASS;
	public static final DeferredBlock<Block> WHITE_STAINED_SOUL_GLASS_PANE;
	public static final DeferredBlock<Block> GREY_STAINED_SOUL_GLASS;
	public static final DeferredBlock<Block> GREY_STAINED_SOUL_GLASS_PANE;
	public static final DeferredBlock<Block> BLACK_STAINED_SOUL_GLASS;
	public static final DeferredBlock<Block> BLACK_STAINED_SOUL_GLASS_PANE;
	public static final DeferredBlock<Block> RED_STAINED_SOUL_GLASS;
	public static final DeferredBlock<Block> RED_STAINED_SOUL_GLASS_PANE;
	public static final DeferredBlock<Block> ORANGE_STAINED_SOUL_GLASS;
	public static final DeferredBlock<Block> ORANGE_STAINED_SOUL_GLASS_PANE;
	public static final DeferredBlock<Block> YELLOW_STAINED_SOUL_GLASS;
	public static final DeferredBlock<Block> YELLOW_STAINED_SOUL_GLASS_PANE;
	public static final DeferredBlock<Block> LIME_STAINED_SOUL_GLASS;
	public static final DeferredBlock<Block> LIME_STAINED_SOUL_GLASS_PANE;
	public static final DeferredBlock<Block> GREEN_STAINED_SOUL_GLASS;
	public static final DeferredBlock<Block> GREEN_STAINED_SOUL_GLASS_PANE;
	public static final DeferredBlock<Block> CYAN_STAINED_SOUL_GLASS;
	public static final DeferredBlock<Block> CYAN_STAINED_SOUL_GLASS_PANE;
	public static final DeferredBlock<Block> LIGHT_BLUE_STAINED_SOUL_GLASS;
	public static final DeferredBlock<Block> LIGHT_BLUE_STAINED_SOUL_GLASS_PANE;
	public static final DeferredBlock<Block> BLUE_STAINED_SOUL_GLASS;
	public static final DeferredBlock<Block> BLUE_STAINED_SOUL_GLASS_PANE;
	public static final DeferredBlock<Block> PURPLE_STAINED_SOUL_GLASS;
	public static final DeferredBlock<Block> PURPLE_STAINED_SOUL_GLASS_PANE;
	public static final DeferredBlock<Block> MAGENTA_STAINED_SOUL_GLASS;
	public static final DeferredBlock<Block> MAGENTA_STAINED_SOUL_GLASS_PANE;
	public static final DeferredBlock<Block> PINK_STAINED_SOUL_GLASS;
	public static final DeferredBlock<Block> PINK_STAINED_SOUL_GLASS_PANE;
	public static final DeferredBlock<Block> DARK_GREY_STAINED_SOUL_GLASS;
	public static final DeferredBlock<Block> DARK_GREY_STAINED_SOUL_GLASS_PANE;
	public static final DeferredBlock<Block> BROWN_STAINED_SOUL_GLASS;
	public static final DeferredBlock<Block> BROWN_STAINED_SOUL_GLASS_PANE;
	public static final DeferredBlock<Block> SANDSTONE_BRICKS;
	public static final DeferredBlock<Block> SANDSTONE_BRICK_STAIRS;
	public static final DeferredBlock<Block> SANDSTONE_BRICK_SLAB;
	public static final DeferredBlock<Block> SANDSTONE_BRICK_WALL;
	public static final DeferredBlock<Block> RED_SANDSTONE_BRICKS;
	public static final DeferredBlock<Block> RED_SANDSTONE_BRICK_STAIRS;
	public static final DeferredBlock<Block> RED_SANDSTONE_BRICK_SLAB;
	public static final DeferredBlock<Block> RED_SANDSTONE_BRICK_WALL;
	public static final DeferredBlock<Block> SOUL_SLATE;
	public static final DeferredBlock<Block> SOUL_SLATE_BRICKS;
	public static final DeferredBlock<Block> CHISELED_SOUL_SLATE;
	public static final DeferredBlock<Block> SOUL_SLATE_BRICK_STAIRS;
	public static final DeferredBlock<Block> SOUL_SLATE_BRICK_SLAB;
	public static final DeferredBlock<Block> SOUL_SLATE_BRICK_WALL;
	public static final DeferredBlock<Block> PURPUR_WALL;
	public static final DeferredBlock<Block> ECHO_CRYSTAL;
	public static final DeferredBlock<Block> CHISELED_END_STONE_BRICKS;
	public static final DeferredBlock<Block> HANGING_TORCHFLOWER;
	public static final DeferredBlock<Block> RAW_SALT;
	public static final DeferredBlock<Block> SALT_CRYSTAL;
	public static final DeferredBlock<Block> SALT_GROWTH;
	public static final DeferredBlock<Block> WROUGHT_IRON;
	public static final DeferredBlock<Block> STONE_PILLAR;
	public static final DeferredBlock<Block> CHISELED_RED_NETHER_BRICK;
	public static final DeferredBlock<Block> CACTUS_WOOD;
	public static final DeferredBlock<Block> CACTUS_W_PLANKS;
	public static final DeferredBlock<Block> CACTUS_W_STAIRS;
	public static final DeferredBlock<Block> CACTUS_W_SLAB;
	public static final DeferredBlock<Block> CACTUS_W_FENCE;
	public static final DeferredBlock<Block> CACTUS_W_FENCE_GATE;
	public static final DeferredBlock<Block> CACTUS_W_PRESSURE_PLATE;
	public static final DeferredBlock<Block> CACTUS_W_BUTTON;
	public static final DeferredBlock<Block> POTTED_CHORUS;
	public static final DeferredBlock<Block> VERY_CRACKED_STONE_BRICKS;
	public static final DeferredBlock<Block> DESTROYED_STONE_BRICKS;
	public static final DeferredBlock<Block> CRACKED_BRICKS;
	public static final DeferredBlock<Block> VERY_CRACKED_BRICKS;
	public static final DeferredBlock<Block> DESTROYED_BRICKS;
	public static final DeferredBlock<Block> MOSSY_BRICKS;
	public static final DeferredBlock<Block> CACTUS_WOOD_DOOR;
	public static final DeferredBlock<Block> CACTUS_WOOD_TRAPDOOR;
	public static final DeferredBlock<Block> LACE_BANNER;
	public static final DeferredBlock<Block> WHITE_LACE_BANNER;
	public static final DeferredBlock<Block> LIGHT_GREY_LACE_BANNER;
	public static final DeferredBlock<Block> GREY_LACE_BANNER;
	public static final DeferredBlock<Block> BLACK_LACE_BANNER;
	public static final DeferredBlock<Block> RED_LACE_BANNER;
	public static final DeferredBlock<Block> ORANGE_LACE_BANNER;
	public static final DeferredBlock<Block> YELLOW_LACE_BANNER;
	public static final DeferredBlock<Block> LIME_LACE_BANNER;
	public static final DeferredBlock<Block> GREEN_LACE_BANNER;
	public static final DeferredBlock<Block> CYAN_LACE_BANNER;
	public static final DeferredBlock<Block> LIGHT_BLUE_LACE_BANNER;
	public static final DeferredBlock<Block> BLUE_LACE_BANNER;
	public static final DeferredBlock<Block> PURPLE_LACE_BANNER;
	public static final DeferredBlock<Block> MAGENTA_LACE_BANNER;
	public static final DeferredBlock<Block> PINK_LACE_BANNER;
	public static final DeferredBlock<Block> BROWN_LACE_BANNER;
	public static final DeferredBlock<Block> PRISMARINE_BRICK_WALL;
	public static final DeferredBlock<Block> DARK_PRISMARINE_WALL;
	public static final DeferredBlock<Block> PRISMARINE_PILLAR;
	public static final DeferredBlock<Block> DARK_PRISMARINE_PILLAR;
	public static final DeferredBlock<Block> CHISELED_PRISMARINE;
	public static final DeferredBlock<Block> SALT_CRYSTAL_EMISSIVE;
	public static final DeferredBlock<Block> SOUL_MAGMA;
	public static final DeferredBlock<Block> RED_LACE_CARPET;
	public static final DeferredBlock<Block> ORANGE_LACE_CARPET;
	public static final DeferredBlock<Block> YELLOW_LACE_CARPET;
	public static final DeferredBlock<Block> LIME_LACE_CARPET;
	public static final DeferredBlock<Block> GREEN_LACE_CARPET;
	public static final DeferredBlock<Block> CYAN_LACE_CARPET;
	public static final DeferredBlock<Block> LIGHT_BLUE_LACE_CARPET;
	public static final DeferredBlock<Block> BLUE_LACE_CARPET;
	public static final DeferredBlock<Block> PURPLE_LACE_CARPET;
	public static final DeferredBlock<Block> MAGENTA_LACE_CARPET;
	public static final DeferredBlock<Block> PINK_LACE_CARPET;
	public static final DeferredBlock<Block> BROWN_LACE_CARPET;
	public static final DeferredBlock<Block> BLACK_LACE_CARPET;
	public static final DeferredBlock<Block> GREY_LACE_CARPET;
	public static final DeferredBlock<Block> LIGHT_GREY_LACE_CARPET;
	public static final DeferredBlock<Block> WHITE_LACE_CARPET;
	public static final DeferredBlock<Block> BUS_LACE_CARPET;
	public static final DeferredBlock<Block> LACE_CARPET;
	public static final DeferredBlock<Block> CHISELED_STONE;
	public static final DeferredBlock<Block> CHISELED_DEEPSLATE_BRICKS;
	public static final DeferredBlock<Block> CHISELED_BLACKSTONE_BRICKS;
	public static final DeferredBlock<Block> HOOK;
	public static final DeferredBlock<Block> DUCK_WEED;
	public static final DeferredBlock<Block> FOUNTAIN_GRASS;
	public static final DeferredBlock<Block> PURPLE_FOUNTAIN_GRASS;
	public static final DeferredBlock<Block> SWAMP_GRASS;
	public static final DeferredBlock<Block> GREEN_DESERT_BUSH;
	public static final DeferredBlock<Block> PURPLE_DESERT_BUSH;
	public static final DeferredBlock<Block> BRACE;
	public static final DeferredBlock<Block> COPPER_BARS;
	public static final DeferredBlock<Block> EXPOSED_COPPER_BARS;
	public static final DeferredBlock<Block> WEATHERED_COPPER_BARS;
	public static final DeferredBlock<Block> OXIDISED_COPPER_BARS;
	public static final DeferredBlock<Block> IRON_GATE;
	public static final DeferredBlock<Block> WEATHERED_WROUGHT_IRON;
	public static final DeferredBlock<Block> WROUGHT_IRON_BARS;
	public static final DeferredBlock<Block> FROSTED_GLASS;
	public static final DeferredBlock<Block> RUSTED_WROUGHT_IRON;
	public static final DeferredBlock<Block> EXPOSED_WROUGHT_IRON;
	public static final DeferredBlock<Block> STONE_WALL;
	public static final DeferredBlock<Block> DARK_SEA_LANTERN;
	public static final DeferredBlock<Block> WROUGHT_IRON_GATE;
	public static final DeferredBlock<Block> WAXED_WROUGHT_IRON;
	public static final DeferredBlock<Block> WAXED_WEATHERED_WROUGHT_IRON;
	public static final DeferredBlock<Block> WAXED_EXPOSED_WROUGHT_IRON;
	public static final DeferredBlock<Block> WAXED_RUSTED_WROUGHT_IRON;
	public static final DeferredBlock<Block> WAXED_COPPER_BARS;
	public static final DeferredBlock<Block> WAXED_EXPOSED_COPPER_BARS;
	public static final DeferredBlock<Block> WAXED_WEATHERED_COPPER_BARS;
	public static final DeferredBlock<Block> WAXED_OXIDISED_COPPER_BARS;
	public static final DeferredBlock<Block> EXPOSED_WROUGHT_IRON_BARS;
	public static final DeferredBlock<Block> WEATHERED_WROUGHT_IRON_BARS;
	public static final DeferredBlock<Block> RUSTED_WROUGHT_IRON_BARS;
	public static final DeferredBlock<Block> WAXED_WROUGHT_IRON_BARS;
	public static final DeferredBlock<Block> WAXED_WEATHERED_WROUGHT_IRON_BARS;
	public static final DeferredBlock<Block> WAXED_EXPOSED_WROUGHT_IRON_BARS;
	public static final DeferredBlock<Block> WAXED_RUSTED_WROUGHT_IRON_BARS;
	public static final DeferredBlock<Block> EXPOSED_WROUGHT_IRON_GATE;
	public static final DeferredBlock<Block> WEATHERED_WROUGHT_IRON_GATE;
	public static final DeferredBlock<Block> RUSTED_WROUGHT_IRON_GATE;
	public static final DeferredBlock<Block> WAXED_WROUGHT_IRON_GATE;
	public static final DeferredBlock<Block> WAXED_EXPOSED_WROUGHT_IRON_GATE;
	public static final DeferredBlock<Block> WAXED_WEATHERED_WROUGHT_IRON_GATE;
	public static final DeferredBlock<Block> WAXED_RUSTED_WROUGHT_IRON_GATE;
	public static final DeferredBlock<Block> TEMPBEAM;
	static {
		CUT_ANDESITE = register("cut_andesite", CutAndesiteBlock::new);
		CUT_ANDESITE_STAIRS = register("cut_andesite_stairs", CutAndesiteStairsBlock::new);
		CUT_ANDESITE_SLAB = register("cut_andesite_slab", CutAndesiteSlabBlock::new);
		CUT_GRANITE = register("cut_granite", CutGraniteBlock::new);
		CUT_GRANITE_STAIRS = register("cut_granite_stairs", CutGraniteStairsBlock::new);
		CUT_GRANITE_SLAB = register("cut_granite_slab", CutGraniteSlabBlock::new);
		SWAMPVINE = register("swampvine", SwampvineBlock::new);
		LAMP = register("lamp", LampBlock::new);
		TEST = register("test", TESTBlock::new);
		POLISHED_CALCITE = register("polished_calcite", PolishedCalciteBlock::new);
		POLISHED_CALCITE_STAIRS = register("polished_calcite_stairs", PolishedCalciteStairsBlock::new);
		POLISHED_CALCITE_SLAB = register("polished_calcite_slab", PolishedCalciteSlabBlock::new);
		POLISHED_CALCITE_WALL = register("polished_calcite_wall", PolishedCalciteWallBlock::new);
		CALCITE_STAIRS = register("calcite_stairs", CalciteStairsBlock::new);
		CALCITE_SLAB = register("calcite_slab", CalciteSlabBlock::new);
		CALCITE_BRICKS = register("calcite_bricks", CalciteBricksBlock::new);
		CALCITE_WALL = register("calcite_wall", CalciteWallBlock::new);
		CALCITE_BRICK_STAIRS = register("calcite_brick_stairs", CalciteBrickStairsBlock::new);
		CALCITE_BRICK_SLAB = register("calcite_brick_slab", CalciteBrickSlabBlock::new);
		CALCITE_BRICK_WALL = register("calcite_brick_wall", CalciteBrickWallBlock::new);
		CUT_DIORITE = register("cut_diorite", CutDioriteBlock::new);
		CUT_DIORITE_STAIRS = register("cut_diorite_stairs", CutDioriteStairsBlock::new);
		CUT_DIORITE_SLAB = register("cut_diorite_slab", CutDioriteSlabBlock::new);
		CRACKED_MUD_BRICKS = register("cracked_mud_bricks", CrackedMudBricksBlock::new);
		CRACKED_END_BRICKS = register("cracked_end_bricks", CrackedEndBricksBlock::new);
		CRACKED_QUARTZ_BRICKS = register("cracked_quartz_bricks", CrackedQuartzBricksBlock::new);
		QUARTZ_BRICK_STAIRS = register("quartz_brick_stairs", QuartzBrickStairsBlock::new);
		QUARTZ_BRICK_SLAB = register("quartz_brick_slab", QuartzBrickSlabBlock::new);
		QUARTZ_BRICK_WALL = register("quartz_brick_wall", QuartzBrickWallBlock::new);
		SMOOTH_STONE_STAIRS = register("smooth_stone_stairs", SmoothStoneStairsBlock::new);
		CRACKED_RED_NETHER_BRICK = register("cracked_red_nether_brick", CrackedRedNetherBrickBlock::new);
		BRACKET = register("bracket", BracketBlock::new);
		SCONCE = register("sconce", SconceBlock::new);
		POLISHED_DRIPSTONE = register("polished_dripstone", PolishedDripstoneBlock::new);
		POLISHED_DRIPSTONE_STAIRS = register("polished_dripstone_stairs", PolishedDripstoneStairsBlock::new);
		POLISHED_DRIPSTONE_SLAB = register("polished_dripstone_slab", PolishedDripstoneSlabBlock::new);
		POLISHED_DRIPSTONE_WALL = register("polished_dripstone_wall", PolishedDripstoneWallBlock::new);
		DRIPSTONE_BRICKS = register("dripstone_bricks", DripstoneBricksBlock::new);
		DRIPSTONE_BRICK_STAIRS = register("dripstone_brick_stairs", DripstoneBrickStairsBlock::new);
		DRIPSTONE_BRICK_SLAB = register("dripstone_brick_slab", DripstoneBrickSlabBlock::new);
		DRIPSTONE_BRICK_WALL = register("dripstone_brick_wall", DripstoneBrickWallBlock::new);
		DRIPSTONE_STAIRS = register("dripstone_stairs", DripstoneStairsBlock::new);
		DRIPSTONE_SLAB = register("dripstone_slab", DripstoneSlabBlock::new);
		DRIPSTONE_WALL = register("dripstone_wall", DripstoneWallBlock::new);
		CRACKED_DRIPSTONE_BRICKS = register("cracked_dripstone_bricks", CrackedDripstoneBricksBlock::new);
		CRACKED_CALCITE_BRICKS = register("cracked_calcite_bricks", CrackedCalciteBricksBlock::new);
		CHAIN_LEFT = register("chain_left", ChainLeftBlock::new);
		CHAIN_MID = register("chain_mid", ChainMidBlock::new);
		CHAIN_CONNECTED = register("chain_connected", ChainConnectedBlock::new);
		ICE_BRICKS = register("ice_bricks", IceBricksBlock::new);
		ICE_BRICK_STAIRS = register("ice_brick_stairs", IceBrickStairsBlock::new);
		ICE_BRICK_SLAB = register("ice_brick_slab", IceBrickSlabBlock::new);
		ICE_BRICK_WALL = register("ice_brick_wall", IceBrickWallBlock::new);
		CUT_SMOOTH_STONE = register("cut_smooth_stone", CutSmoothStoneBlock::new);
		CUT_SMOOTH_STONE_STAIRS = register("cut_smooth_stone_stairs", CutSmoothStoneStairsBlock::new);
		CUT_SMOOTH_STONE_SLAB = register("cut_smooth_stone_slab", CutSmoothStoneSlabBlock::new);
		SMOOTH_STONE_WALL = register("smooth_stone_wall", SmoothStoneWallBlock::new);
		ICICLE_TIP = register("icicle_tip", IcicleTipBlock::new);
		ICICLE_FRUSTUM = register("icicle_frustum", IcicleFrustumBlock::new);
		ICICLE_MIDDLE = register("icicle_middle", IcicleMiddleBlock::new);
		ICICLE_BASE = register("icicle_base", IcicleBaseBlock::new);
		CHORUS_PLANKS = register("chorus_planks", ChorusPlanksBlock::new);
		CHORUS_STAIRS = register("chorus_stairs", ChorusStairsBlock::new);
		CHORUS_SLAB = register("chorus_slab", ChorusSlabBlock::new);
		CHORUS_FENCE = register("chorus_fence", ChorusFenceBlock::new);
		CHORUS_FENCE_GATE = register("chorus_fence_gate", ChorusFenceGateBlock::new);
		CHORUS_PRESSURE_PLATE = register("chorus_pressure_plate", ChorusPressurePlateBlock::new);
		CHORUS_BUTTON = register("chorus_button", ChorusButtonBlock::new);
		CHORUS_DOOR = register("chorus_door", ChorusDoorBlock::new);
		CHORUS_TRAPDOOR = register("chorus_trapdoor", ChorusTrapdoorBlock::new);
		SOUL_LAMP = register("soul_lamp", SoulLampBlock::new);
		SOUL_SCONCE = register("soul_sconce", SoulSconceBlock::new);
		OAK_BEAM = register("oak_beam", OakBeamBlock::new);
		SPRUCE_BEAM = register("spruce_beam", SpruceBeamBlock::new);
		BIRCH_BEAM = register("birch_beam", BirchBeamBlock::new);
		DARK_OAK_BEAM = register("dark_oak_beam", DarkOakBeamBlock::new);
		ACACIA_BEAM = register("acacia_beam", AcaciaBeamBlock::new);
		MANGROVE_BEAM = register("mangrove_beam", MangroveBeamBlock::new);
		CHERRY_BEAM = register("cherry_beam", CherryBeamBlock::new);
		JUNGLE_BEAM = register("jungle_beam", JungleBeamBlock::new);
		BAMBOO_BEAM = register("bamboo_beam", BambooBeamBlock::new);
		CRIMSON_BEAM = register("crimson_beam", CrimsonBeamBlock::new);
		WARPED_BEAM = register("warped_beam", WarpedBeamBlock::new);
		CUT_AMETHYST = register("cut_amethyst", CutAmethystBlock::new);
		END_STONE_STAIRS = register("end_stone_stairs", EndStoneStairsBlock::new);
		END_STONE_SLAB = register("end_stone_slab", EndStoneSlabBlock::new);
		END_STONE_WALL = register("end_stone_wall", EndStoneWallBlock::new);
		SOUL_GLASS = register("soul_glass", SoulGlassBlock::new);
		SOUL_GLASS_PANE = register("soul_glass_pane", SoulGlassPaneBlock::new);
		WHITE_STAINED_SOUL_GLASS = register("white_stained_soul_glass", WhiteStainedSoulGlassBlock::new);
		WHITE_STAINED_SOUL_GLASS_PANE = register("white_stained_soul_glass_pane", WhiteStainedSoulGlassPaneBlock::new);
		GREY_STAINED_SOUL_GLASS = register("grey_stained_soul_glass", GreyStainedSoulGlassBlock::new);
		GREY_STAINED_SOUL_GLASS_PANE = register("grey_stained_soul_glass_pane", GreyStainedSoulGlassPaneBlock::new);
		BLACK_STAINED_SOUL_GLASS = register("black_stained_soul_glass", BlackStainedSoulGlassBlock::new);
		BLACK_STAINED_SOUL_GLASS_PANE = register("black_stained_soul_glass_pane", BlackStainedSoulGlassPaneBlock::new);
		RED_STAINED_SOUL_GLASS = register("red_stained_soul_glass", RedStainedSoulGlassBlock::new);
		RED_STAINED_SOUL_GLASS_PANE = register("red_stained_soul_glass_pane", RedStainedSoulGlassPaneBlock::new);
		ORANGE_STAINED_SOUL_GLASS = register("orange_stained_soul_glass", OrangeStainedSoulGlassBlock::new);
		ORANGE_STAINED_SOUL_GLASS_PANE = register("orange_stained_soul_glass_pane", OrangeStainedSoulGlassPaneBlock::new);
		YELLOW_STAINED_SOUL_GLASS = register("yellow_stained_soul_glass", YellowStainedSoulGlassBlock::new);
		YELLOW_STAINED_SOUL_GLASS_PANE = register("yellow_stained_soul_glass_pane", YellowStainedSoulGlassPaneBlock::new);
		LIME_STAINED_SOUL_GLASS = register("lime_stained_soul_glass", LimeStainedSoulGlassBlock::new);
		LIME_STAINED_SOUL_GLASS_PANE = register("lime_stained_soul_glass_pane", LimeStainedSoulGlassPaneBlock::new);
		GREEN_STAINED_SOUL_GLASS = register("green_stained_soul_glass", GreenStainedSoulGlassBlock::new);
		GREEN_STAINED_SOUL_GLASS_PANE = register("green_stained_soul_glass_pane", GreenStainedSoulGlassPaneBlock::new);
		CYAN_STAINED_SOUL_GLASS = register("cyan_stained_soul_glass", CyanStainedSoulGlassBlock::new);
		CYAN_STAINED_SOUL_GLASS_PANE = register("cyan_stained_soul_glass_pane", CyanStainedSoulGlassPaneBlock::new);
		LIGHT_BLUE_STAINED_SOUL_GLASS = register("light_blue_stained_soul_glass", LightBlueStainedSoulGlassBlock::new);
		LIGHT_BLUE_STAINED_SOUL_GLASS_PANE = register("light_blue_stained_soul_glass_pane", LightBlueStainedSoulGlassPaneBlock::new);
		BLUE_STAINED_SOUL_GLASS = register("blue_stained_soul_glass", BlueStainedSoulGlassBlock::new);
		BLUE_STAINED_SOUL_GLASS_PANE = register("blue_stained_soul_glass_pane", BlueStainedSoulGlassPaneBlock::new);
		PURPLE_STAINED_SOUL_GLASS = register("purple_stained_soul_glass", PurpleStainedSoulGlassBlock::new);
		PURPLE_STAINED_SOUL_GLASS_PANE = register("purple_stained_soul_glass_pane", PurpleStainedSoulGlassPaneBlock::new);
		MAGENTA_STAINED_SOUL_GLASS = register("magenta_stained_soul_glass", MagentaStainedSoulGlassBlock::new);
		MAGENTA_STAINED_SOUL_GLASS_PANE = register("magenta_stained_soul_glass_pane", MagentaStainedSoulGlassPaneBlock::new);
		PINK_STAINED_SOUL_GLASS = register("pink_stained_soul_glass", PinkStainedSoulGlassBlock::new);
		PINK_STAINED_SOUL_GLASS_PANE = register("pink_stained_soul_glass_pane", PinkStainedSoulGlassPaneBlock::new);
		DARK_GREY_STAINED_SOUL_GLASS = register("dark_grey_stained_soul_glass", DarkGreyStainedSoulGlassBlock::new);
		DARK_GREY_STAINED_SOUL_GLASS_PANE = register("dark_grey_stained_soul_glass_pane", DarkGreyStainedSoulGlassPaneBlock::new);
		BROWN_STAINED_SOUL_GLASS = register("brown_stained_soul_glass", BrownStainedSoulGlassBlock::new);
		BROWN_STAINED_SOUL_GLASS_PANE = register("brown_stained_soul_glass_pane", BrownStainedSoulGlassPaneBlock::new);
		SANDSTONE_BRICKS = register("sandstone_bricks", SandstoneBricksBlock::new);
		SANDSTONE_BRICK_STAIRS = register("sandstone_brick_stairs", SandstoneBrickStairsBlock::new);
		SANDSTONE_BRICK_SLAB = register("sandstone_brick_slab", SandstoneBrickSlabBlock::new);
		SANDSTONE_BRICK_WALL = register("sandstone_brick_wall", SandstoneBrickWallBlock::new);
		RED_SANDSTONE_BRICKS = register("red_sandstone_bricks", RedSandstoneBricksBlock::new);
		RED_SANDSTONE_BRICK_STAIRS = register("red_sandstone_brick_stairs", RedSandstoneBrickStairsBlock::new);
		RED_SANDSTONE_BRICK_SLAB = register("red_sandstone_brick_slab", RedSandstoneBrickSlabBlock::new);
		RED_SANDSTONE_BRICK_WALL = register("red_sandstone_brick_wall", RedSandstoneBrickWallBlock::new);
		SOUL_SLATE = register("soul_slate", SoulSlateBlock::new);
		SOUL_SLATE_BRICKS = register("soul_slate_bricks", SoulSlateBricksBlock::new);
		CHISELED_SOUL_SLATE = register("chiseled_soul_slate", ChiseledSoulSlateBlock::new);
		SOUL_SLATE_BRICK_STAIRS = register("soul_slate_brick_stairs", SoulSlateBrickStairsBlock::new);
		SOUL_SLATE_BRICK_SLAB = register("soul_slate_brick_slab", SoulSlateBrickSlabBlock::new);
		SOUL_SLATE_BRICK_WALL = register("soul_slate_brick_wall", SoulSlateBrickWallBlock::new);
		PURPUR_WALL = register("purpur_wall", PurpurWallBlock::new);
		ECHO_CRYSTAL = register("echo_crystal", EchoCrystalBlock::new);
		CHISELED_END_STONE_BRICKS = register("chiseled_end_stone_bricks", ChiseledEndStoneBricksBlock::new);
		HANGING_TORCHFLOWER = register("hanging_torchflower", HangingTorchflowerBlock::new);
		RAW_SALT = register("raw_salt", RawSaltBlock::new);
		SALT_CRYSTAL = register("salt_crystal", SaltCrystalBlock::new);
		SALT_GROWTH = register("salt_growth", SaltGrowthBlock::new);
		WROUGHT_IRON = register("wrought_iron", WroughtIronBlock::new);
		STONE_PILLAR = register("stone_pillar", StonePillarBlock::new);
		CHISELED_RED_NETHER_BRICK = register("chiseled_red_nether_brick", ChiseledRedNetherBrickBlock::new);
		CACTUS_WOOD = register("cactus_wood", CactusWoodBlock::new);
		CACTUS_W_PLANKS = register("cactus_w_planks", CactusWPlanksBlock::new);
		CACTUS_W_STAIRS = register("cactus_w_stairs", CactusWStairsBlock::new);
		CACTUS_W_SLAB = register("cactus_w_slab", CactusWSlabBlock::new);
		CACTUS_W_FENCE = register("cactus_w_fence", CactusWFenceBlock::new);
		CACTUS_W_FENCE_GATE = register("cactus_w_fence_gate", CactusWFenceGateBlock::new);
		CACTUS_W_PRESSURE_PLATE = register("cactus_w_pressure_plate", CactusWPressurePlateBlock::new);
		CACTUS_W_BUTTON = register("cactus_w_button", CactusWButtonBlock::new);
		POTTED_CHORUS = register("potted_chorus", PottedChorusBlock::new);
		VERY_CRACKED_STONE_BRICKS = register("very_cracked_stone_bricks", VeryCrackedStoneBricksBlock::new);
		DESTROYED_STONE_BRICKS = register("destroyed_stone_bricks", DestroyedStoneBricksBlock::new);
		CRACKED_BRICKS = register("cracked_bricks", CrackedBricksBlock::new);
		VERY_CRACKED_BRICKS = register("very_cracked_bricks", VeryCrackedBricksBlock::new);
		DESTROYED_BRICKS = register("destroyed_bricks", DestroyedBricksBlock::new);
		MOSSY_BRICKS = register("mossy_bricks", MossyBricksBlock::new);
		CACTUS_WOOD_DOOR = register("cactus_wood_door", CactusWoodDoorBlock::new);
		CACTUS_WOOD_TRAPDOOR = register("cactus_wood_trapdoor", CactusWoodTrapdoorBlock::new);
		LACE_BANNER = register("lace_banner", LaceBannerBlock::new);
		WHITE_LACE_BANNER = register("white_lace_banner", WhiteLaceBannerBlock::new);
		LIGHT_GREY_LACE_BANNER = register("light_grey_lace_banner", LightGreyLaceBannerBlock::new);
		GREY_LACE_BANNER = register("grey_lace_banner", GreyLaceBannerBlock::new);
		BLACK_LACE_BANNER = register("black_lace_banner", BlackLaceBannerBlock::new);
		RED_LACE_BANNER = register("red_lace_banner", RedLaceBannerBlock::new);
		ORANGE_LACE_BANNER = register("orange_lace_banner", OrangeLaceBannerBlock::new);
		YELLOW_LACE_BANNER = register("yellow_lace_banner", YellowLaceBannerBlock::new);
		LIME_LACE_BANNER = register("lime_lace_banner", LimeLaceBannerBlock::new);
		GREEN_LACE_BANNER = register("green_lace_banner", GreenLaceBannerBlock::new);
		CYAN_LACE_BANNER = register("cyan_lace_banner", CyanLaceBannerBlock::new);
		LIGHT_BLUE_LACE_BANNER = register("light_blue_lace_banner", LightBlueLaceBannerBlock::new);
		BLUE_LACE_BANNER = register("blue_lace_banner", BlueLaceBannerBlock::new);
		PURPLE_LACE_BANNER = register("purple_lace_banner", PurpleLaceBannerBlock::new);
		MAGENTA_LACE_BANNER = register("magenta_lace_banner", MagentaLaceBannerBlock::new);
		PINK_LACE_BANNER = register("pink_lace_banner", PinkLaceBannerBlock::new);
		BROWN_LACE_BANNER = register("brown_lace_banner", BrownLaceBannerBlock::new);
		PRISMARINE_BRICK_WALL = register("prismarine_brick_wall", PrismarineBrickWallBlock::new);
		DARK_PRISMARINE_WALL = register("dark_prismarine_wall", DarkPrismarineWallBlock::new);
		PRISMARINE_PILLAR = register("prismarine_pillar", PrismarinePillarBlock::new);
		DARK_PRISMARINE_PILLAR = register("dark_prismarine_pillar", DarkPrismarinePillarBlock::new);
		CHISELED_PRISMARINE = register("chiseled_prismarine", ChiseledPrismarineBlock::new);
		SALT_CRYSTAL_EMISSIVE = register("salt_crystal_emissive", SaltCrystalEmissiveBlock::new);
		SOUL_MAGMA = register("soul_magma", SoulMagmaBlock::new);
		RED_LACE_CARPET = register("red_lace_carpet", RedLaceCarpetBlock::new);
		ORANGE_LACE_CARPET = register("orange_lace_carpet", OrangeLaceCarpetBlock::new);
		YELLOW_LACE_CARPET = register("yellow_lace_carpet", YellowLaceCarpetBlock::new);
		LIME_LACE_CARPET = register("lime_lace_carpet", LimeLaceCarpetBlock::new);
		GREEN_LACE_CARPET = register("green_lace_carpet", GreenLaceCarpetBlock::new);
		CYAN_LACE_CARPET = register("cyan_lace_carpet", CyanLaceCarpetBlock::new);
		LIGHT_BLUE_LACE_CARPET = register("light_blue_lace_carpet", LightBlueLaceCarpetBlock::new);
		BLUE_LACE_CARPET = register("blue_lace_carpet", BlueLaceCarpetBlock::new);
		PURPLE_LACE_CARPET = register("purple_lace_carpet", PurpleLaceCarpetBlock::new);
		MAGENTA_LACE_CARPET = register("magenta_lace_carpet", MagentaLaceCarpetBlock::new);
		PINK_LACE_CARPET = register("pink_lace_carpet", PinkLaceCarpetBlock::new);
		BROWN_LACE_CARPET = register("brown_lace_carpet", BrownLaceCarpetBlock::new);
		BLACK_LACE_CARPET = register("black_lace_carpet", BlackLaceCarpetBlock::new);
		GREY_LACE_CARPET = register("grey_lace_carpet", GreyLaceCarpetBlock::new);
		LIGHT_GREY_LACE_CARPET = register("light_grey_lace_carpet", LightGreyLaceCarpetBlock::new);
		WHITE_LACE_CARPET = register("white_lace_carpet", WhiteLaceCarpetBlock::new);
		BUS_LACE_CARPET = register("bus_lace_carpet", BusLaceCarpetBlock::new);
		LACE_CARPET = register("lace_carpet", LaceCarpetBlock::new);
		CHISELED_STONE = register("chiseled_stone", ChiseledStoneBlock::new);
		CHISELED_DEEPSLATE_BRICKS = register("chiseled_deepslate_bricks", ChiseledDeepslateBricksBlock::new);
		CHISELED_BLACKSTONE_BRICKS = register("chiseled_blackstone_bricks", ChiseledBlackstoneBricksBlock::new);
		HOOK = register("hook", HookBlock::new);
		DUCK_WEED = register("duck_weed", DuckWeedBlock::new);
		FOUNTAIN_GRASS = register("fountain_grass", FountainGrassBlock::new);
		PURPLE_FOUNTAIN_GRASS = register("purple_fountain_grass", PurpleFountainGrassBlock::new);
		SWAMP_GRASS = register("swamp_grass", SwampGrassBlock::new);
		GREEN_DESERT_BUSH = register("green_desert_bush", GreenDesertBushBlock::new);
		PURPLE_DESERT_BUSH = register("purple_desert_bush", PurpleDesertBushBlock::new);
		BRACE = register("brace", BraceBlock::new);
		COPPER_BARS = register("copper_bars", CopperBarsBlock::new);
		EXPOSED_COPPER_BARS = register("exposed_copper_bars", ExposedCopperBarsBlock::new);
		WEATHERED_COPPER_BARS = register("weathered_copper_bars", WeatheredCopperBarsBlock::new);
		OXIDISED_COPPER_BARS = register("oxidised_copper_bars", OxidisedCopperBarsBlock::new);
		IRON_GATE = register("iron_gate", IronGateBlock::new);
		WEATHERED_WROUGHT_IRON = register("weathered_wrought_iron", WeatheredWroughtIronBlock::new);
		WROUGHT_IRON_BARS = register("wrought_iron_bars", WroughtIronBarsBlock::new);
		FROSTED_GLASS = register("frosted_glass", FrostedGlassBlock::new);
		RUSTED_WROUGHT_IRON = register("rusted_wrought_iron", RustedWroughtIronBlock::new);
		EXPOSED_WROUGHT_IRON = register("exposed_wrought_iron", ExposedWroughtIronBlock::new);
		STONE_WALL = register("stone_wall", StoneWallBlock::new);
		DARK_SEA_LANTERN = register("dark_sea_lantern", DarkSeaLanternBlock::new);
		WROUGHT_IRON_GATE = register("wrought_iron_gate", WroughtIronGateBlock::new);
		WAXED_WROUGHT_IRON = register("waxed_wrought_iron", WaxedWroughtIronBlock::new);
		WAXED_WEATHERED_WROUGHT_IRON = register("waxed_weathered_wrought_iron", WaxedWeatheredWroughtIronBlock::new);
		WAXED_EXPOSED_WROUGHT_IRON = register("waxed_exposed_wrought_iron", WaxedExposedWroughtIronBlock::new);
		WAXED_RUSTED_WROUGHT_IRON = register("waxed_rusted_wrought_iron", WaxedRustedWroughtIronBlock::new);
		WAXED_COPPER_BARS = register("waxed_copper_bars", WaxedCopperBarsBlock::new);
		WAXED_EXPOSED_COPPER_BARS = register("waxed_exposed_copper_bars", WaxedExposedCopperBarsBlock::new);
		WAXED_WEATHERED_COPPER_BARS = register("waxed_weathered_copper_bars", WaxedWeatheredCopperBarsBlock::new);
		WAXED_OXIDISED_COPPER_BARS = register("waxed_oxidised_copper_bars", WaxedOxidisedCopperBarsBlock::new);
		EXPOSED_WROUGHT_IRON_BARS = register("exposed_wrought_iron_bars", ExposedWroughtIronBarsBlock::new);
		WEATHERED_WROUGHT_IRON_BARS = register("weathered_wrought_iron_bars", WeatheredWroughtIronBarsBlock::new);
		RUSTED_WROUGHT_IRON_BARS = register("rusted_wrought_iron_bars", RustedWroughtIronBarsBlock::new);
		WAXED_WROUGHT_IRON_BARS = register("waxed_wrought_iron_bars", WaxedWroughtIronBarsBlock::new);
		WAXED_WEATHERED_WROUGHT_IRON_BARS = register("waxed_weathered_wrought_iron_bars", WaxedWeatheredWroughtIronBarsBlock::new);
		WAXED_EXPOSED_WROUGHT_IRON_BARS = register("waxed_exposed_wrought_iron_bars", WaxedExposedWroughtIronBarsBlock::new);
		WAXED_RUSTED_WROUGHT_IRON_BARS = register("waxed_rusted_wrought_iron_bars", WaxedRustedWroughtIronBarsBlock::new);
		EXPOSED_WROUGHT_IRON_GATE = register("exposed_wrought_iron_gate", ExposedWroughtIronGateBlock::new);
		WEATHERED_WROUGHT_IRON_GATE = register("weathered_wrought_iron_gate", WeatheredWroughtIronGateBlock::new);
		RUSTED_WROUGHT_IRON_GATE = register("rusted_wrought_iron_gate", RustedWroughtIronGateBlock::new);
		WAXED_WROUGHT_IRON_GATE = register("waxed_wrought_iron_gate", WaxedWroughtIronGateBlock::new);
		WAXED_EXPOSED_WROUGHT_IRON_GATE = register("waxed_exposed_wrought_iron_gate", WaxedExposedWroughtIronGateBlock::new);
		WAXED_WEATHERED_WROUGHT_IRON_GATE = register("waxed_weathered_wrought_iron_gate", WaxedWeatheredWroughtIronGateBlock::new);
		WAXED_RUSTED_WROUGHT_IRON_GATE = register("waxed_rusted_wrought_iron_gate", WaxedRustedWroughtIronGateBlock::new);
		TEMPBEAM = register("tempbeam", TEMPBEAMBlock::new);
	}

	// Start of user code block custom blocks
	// End of user code block custom blocks
	private static <B extends Block> DeferredBlock<B> register(String name, Function<BlockBehaviour.Properties, ? extends B> supplier) {
		return REGISTRY.registerBlock(name, supplier);
	}
}