
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.extrabuildingblocks.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.extrabuildingblocks.item.LaceItem;
import net.mcreator.extrabuildingblocks.ExtraBuildingBlocksMod;

public class ExtraBuildingBlocksModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, ExtraBuildingBlocksMod.MODID);
	public static final RegistryObject<Item> CUT_ANDESITE = block(ExtraBuildingBlocksModBlocks.CUT_ANDESITE);
	public static final RegistryObject<Item> CUT_ANDESITE_STAIRS = block(ExtraBuildingBlocksModBlocks.CUT_ANDESITE_STAIRS);
	public static final RegistryObject<Item> CUT_ANDESITE_SLAB = block(ExtraBuildingBlocksModBlocks.CUT_ANDESITE_SLAB);
	public static final RegistryObject<Item> CUT_GRANITE = block(ExtraBuildingBlocksModBlocks.CUT_GRANITE);
	public static final RegistryObject<Item> CUT_GRANITE_STAIRS = block(ExtraBuildingBlocksModBlocks.CUT_GRANITE_STAIRS);
	public static final RegistryObject<Item> CUT_GRANITE_SLAB = block(ExtraBuildingBlocksModBlocks.CUT_GRANITE_SLAB);
	public static final RegistryObject<Item> SWAMPVINE = block(ExtraBuildingBlocksModBlocks.SWAMPVINE);
	public static final RegistryObject<Item> LAMP = block(ExtraBuildingBlocksModBlocks.LAMP);
	public static final RegistryObject<Item> TEST = block(ExtraBuildingBlocksModBlocks.TEST);
	public static final RegistryObject<Item> POLISHED_CALCITE = block(ExtraBuildingBlocksModBlocks.POLISHED_CALCITE);
	public static final RegistryObject<Item> POLISHED_CALCITE_STAIRS = block(ExtraBuildingBlocksModBlocks.POLISHED_CALCITE_STAIRS);
	public static final RegistryObject<Item> POLISHED_CALCITE_SLAB = block(ExtraBuildingBlocksModBlocks.POLISHED_CALCITE_SLAB);
	public static final RegistryObject<Item> POLISHED_CALCITE_WALL = block(ExtraBuildingBlocksModBlocks.POLISHED_CALCITE_WALL);
	public static final RegistryObject<Item> CALCITE_STAIRS = block(ExtraBuildingBlocksModBlocks.CALCITE_STAIRS);
	public static final RegistryObject<Item> CALCITE_SLAB = block(ExtraBuildingBlocksModBlocks.CALCITE_SLAB);
	public static final RegistryObject<Item> CALCITE_BRICKS = block(ExtraBuildingBlocksModBlocks.CALCITE_BRICKS);
	public static final RegistryObject<Item> CALCITE_WALL = block(ExtraBuildingBlocksModBlocks.CALCITE_WALL);
	public static final RegistryObject<Item> CALCITE_BRICK_STAIRS = block(ExtraBuildingBlocksModBlocks.CALCITE_BRICK_STAIRS);
	public static final RegistryObject<Item> CALCITE_BRICK_SLAB = block(ExtraBuildingBlocksModBlocks.CALCITE_BRICK_SLAB);
	public static final RegistryObject<Item> CALCITE_BRICK_WALL = block(ExtraBuildingBlocksModBlocks.CALCITE_BRICK_WALL);
	public static final RegistryObject<Item> CUT_DIORITE = block(ExtraBuildingBlocksModBlocks.CUT_DIORITE);
	public static final RegistryObject<Item> CUT_DIORITE_STAIRS = block(ExtraBuildingBlocksModBlocks.CUT_DIORITE_STAIRS);
	public static final RegistryObject<Item> CUT_DIORITE_SLAB = block(ExtraBuildingBlocksModBlocks.CUT_DIORITE_SLAB);
	public static final RegistryObject<Item> CRACKED_MUD_BRICKS = block(ExtraBuildingBlocksModBlocks.CRACKED_MUD_BRICKS);
	public static final RegistryObject<Item> CRACKED_END_BRICKS = block(ExtraBuildingBlocksModBlocks.CRACKED_END_BRICKS);
	public static final RegistryObject<Item> CRACKED_QUARTZ_BRICKS = block(ExtraBuildingBlocksModBlocks.CRACKED_QUARTZ_BRICKS);
	public static final RegistryObject<Item> QUARTZ_BRICK_STAIRS = block(ExtraBuildingBlocksModBlocks.QUARTZ_BRICK_STAIRS);
	public static final RegistryObject<Item> QUARTZ_BRICK_SLAB = block(ExtraBuildingBlocksModBlocks.QUARTZ_BRICK_SLAB);
	public static final RegistryObject<Item> QUARTZ_BRICK_WALL = block(ExtraBuildingBlocksModBlocks.QUARTZ_BRICK_WALL);
	public static final RegistryObject<Item> SMOOTH_STONE_STAIRS = block(ExtraBuildingBlocksModBlocks.SMOOTH_STONE_STAIRS);
	public static final RegistryObject<Item> CRACKED_RED_NETHER_BRICK = block(ExtraBuildingBlocksModBlocks.CRACKED_RED_NETHER_BRICK);
	public static final RegistryObject<Item> BRACKET = block(ExtraBuildingBlocksModBlocks.BRACKET);
	public static final RegistryObject<Item> SCONCE = block(ExtraBuildingBlocksModBlocks.SCONCE);
	public static final RegistryObject<Item> POLISHED_DRIPSTONE = block(ExtraBuildingBlocksModBlocks.POLISHED_DRIPSTONE);
	public static final RegistryObject<Item> POLISHED_DRIPSTONE_STAIRS = block(ExtraBuildingBlocksModBlocks.POLISHED_DRIPSTONE_STAIRS);
	public static final RegistryObject<Item> POLISHED_DRIPSTONE_SLAB = block(ExtraBuildingBlocksModBlocks.POLISHED_DRIPSTONE_SLAB);
	public static final RegistryObject<Item> POLISHED_DRIPSTONE_WALL = block(ExtraBuildingBlocksModBlocks.POLISHED_DRIPSTONE_WALL);
	public static final RegistryObject<Item> DRIPSTONE_BRICKS = block(ExtraBuildingBlocksModBlocks.DRIPSTONE_BRICKS);
	public static final RegistryObject<Item> DRIPSTONE_BRICK_STAIRS = block(ExtraBuildingBlocksModBlocks.DRIPSTONE_BRICK_STAIRS);
	public static final RegistryObject<Item> DRIPSTONE_BRICK_SLAB = block(ExtraBuildingBlocksModBlocks.DRIPSTONE_BRICK_SLAB);
	public static final RegistryObject<Item> DRIPSTONE_BRICK_WALL = block(ExtraBuildingBlocksModBlocks.DRIPSTONE_BRICK_WALL);
	public static final RegistryObject<Item> DRIPSTONE_STAIRS = block(ExtraBuildingBlocksModBlocks.DRIPSTONE_STAIRS);
	public static final RegistryObject<Item> DRIPSTONE_SLAB = block(ExtraBuildingBlocksModBlocks.DRIPSTONE_SLAB);
	public static final RegistryObject<Item> DRIPSTONE_WALL = block(ExtraBuildingBlocksModBlocks.DRIPSTONE_WALL);
	public static final RegistryObject<Item> CRACKED_DRIPSTONE_BRICKS = block(ExtraBuildingBlocksModBlocks.CRACKED_DRIPSTONE_BRICKS);
	public static final RegistryObject<Item> CRACKED_CALCITE_BRICKS = block(ExtraBuildingBlocksModBlocks.CRACKED_CALCITE_BRICKS);
	public static final RegistryObject<Item> CHAIN_LEFT = block(ExtraBuildingBlocksModBlocks.CHAIN_LEFT);
	public static final RegistryObject<Item> CHAIN_MID = block(ExtraBuildingBlocksModBlocks.CHAIN_MID);
	public static final RegistryObject<Item> CHAIN_CONNECTED = block(ExtraBuildingBlocksModBlocks.CHAIN_CONNECTED);
	public static final RegistryObject<Item> ICE_BRICKS = block(ExtraBuildingBlocksModBlocks.ICE_BRICKS);
	public static final RegistryObject<Item> ICE_BRICK_STAIRS = block(ExtraBuildingBlocksModBlocks.ICE_BRICK_STAIRS);
	public static final RegistryObject<Item> ICE_BRICK_SLAB = block(ExtraBuildingBlocksModBlocks.ICE_BRICK_SLAB);
	public static final RegistryObject<Item> ICE_BRICK_WALL = block(ExtraBuildingBlocksModBlocks.ICE_BRICK_WALL);
	public static final RegistryObject<Item> CUT_SMOOTH_STONE = block(ExtraBuildingBlocksModBlocks.CUT_SMOOTH_STONE);
	public static final RegistryObject<Item> CUT_SMOOTH_STONE_STAIRS = block(ExtraBuildingBlocksModBlocks.CUT_SMOOTH_STONE_STAIRS);
	public static final RegistryObject<Item> CUT_SMOOTH_STONE_SLAB = block(ExtraBuildingBlocksModBlocks.CUT_SMOOTH_STONE_SLAB);
	public static final RegistryObject<Item> SMOOTH_STONE_WALL = block(ExtraBuildingBlocksModBlocks.SMOOTH_STONE_WALL);
	public static final RegistryObject<Item> ICICLE_TIP = block(ExtraBuildingBlocksModBlocks.ICICLE_TIP);
	public static final RegistryObject<Item> ICICLE_FRUSTUM = block(ExtraBuildingBlocksModBlocks.ICICLE_FRUSTUM);
	public static final RegistryObject<Item> ICICLE_MIDDLE = block(ExtraBuildingBlocksModBlocks.ICICLE_MIDDLE);
	public static final RegistryObject<Item> ICICLE_BASE = block(ExtraBuildingBlocksModBlocks.ICICLE_BASE);
	public static final RegistryObject<Item> CHORUS_PLANKS = block(ExtraBuildingBlocksModBlocks.CHORUS_PLANKS);
	public static final RegistryObject<Item> CHORUS_STAIRS = block(ExtraBuildingBlocksModBlocks.CHORUS_STAIRS);
	public static final RegistryObject<Item> CHORUS_SLAB = block(ExtraBuildingBlocksModBlocks.CHORUS_SLAB);
	public static final RegistryObject<Item> CHORUS_FENCE = block(ExtraBuildingBlocksModBlocks.CHORUS_FENCE);
	public static final RegistryObject<Item> CHORUS_FENCE_GATE = block(ExtraBuildingBlocksModBlocks.CHORUS_FENCE_GATE);
	public static final RegistryObject<Item> CHORUS_PRESSURE_PLATE = block(ExtraBuildingBlocksModBlocks.CHORUS_PRESSURE_PLATE);
	public static final RegistryObject<Item> CHORUS_BUTTON = block(ExtraBuildingBlocksModBlocks.CHORUS_BUTTON);
	public static final RegistryObject<Item> CHORUS_DOOR = doubleBlock(ExtraBuildingBlocksModBlocks.CHORUS_DOOR);
	public static final RegistryObject<Item> CHORUS_TRAPDOOR = block(ExtraBuildingBlocksModBlocks.CHORUS_TRAPDOOR);
	public static final RegistryObject<Item> SOUL_LAMP = block(ExtraBuildingBlocksModBlocks.SOUL_LAMP);
	public static final RegistryObject<Item> SOUL_SCONCE = block(ExtraBuildingBlocksModBlocks.SOUL_SCONCE);
	public static final RegistryObject<Item> OAK_BEAM = block(ExtraBuildingBlocksModBlocks.OAK_BEAM);
	public static final RegistryObject<Item> SPRUCE_BEAM = block(ExtraBuildingBlocksModBlocks.SPRUCE_BEAM);
	public static final RegistryObject<Item> BIRCH_BEAM = block(ExtraBuildingBlocksModBlocks.BIRCH_BEAM);
	public static final RegistryObject<Item> DARK_OAK_BEAM = block(ExtraBuildingBlocksModBlocks.DARK_OAK_BEAM);
	public static final RegistryObject<Item> ACACIA_BEAM = block(ExtraBuildingBlocksModBlocks.ACACIA_BEAM);
	public static final RegistryObject<Item> MANGROVE_BEAM = block(ExtraBuildingBlocksModBlocks.MANGROVE_BEAM);
	public static final RegistryObject<Item> CHERRY_BEAM = block(ExtraBuildingBlocksModBlocks.CHERRY_BEAM);
	public static final RegistryObject<Item> JUNGLE_BEAM = block(ExtraBuildingBlocksModBlocks.JUNGLE_BEAM);
	public static final RegistryObject<Item> BAMBOO_BEAM = block(ExtraBuildingBlocksModBlocks.BAMBOO_BEAM);
	public static final RegistryObject<Item> CRIMSON_BEAM = block(ExtraBuildingBlocksModBlocks.CRIMSON_BEAM);
	public static final RegistryObject<Item> WARPED_BEAM = block(ExtraBuildingBlocksModBlocks.WARPED_BEAM);
	public static final RegistryObject<Item> CUT_AMETHYST = block(ExtraBuildingBlocksModBlocks.CUT_AMETHYST);
	public static final RegistryObject<Item> END_STONE_STAIRS = block(ExtraBuildingBlocksModBlocks.END_STONE_STAIRS);
	public static final RegistryObject<Item> END_STONE_SLAB = block(ExtraBuildingBlocksModBlocks.END_STONE_SLAB);
	public static final RegistryObject<Item> END_STONE_WALL = block(ExtraBuildingBlocksModBlocks.END_STONE_WALL);
	public static final RegistryObject<Item> SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.SOUL_GLASS);
	public static final RegistryObject<Item> SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.SOUL_GLASS_PANE);
	public static final RegistryObject<Item> WHITE_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.WHITE_STAINED_SOUL_GLASS);
	public static final RegistryObject<Item> WHITE_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.WHITE_STAINED_SOUL_GLASS_PANE);
	public static final RegistryObject<Item> GREY_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.GREY_STAINED_SOUL_GLASS);
	public static final RegistryObject<Item> GREY_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.GREY_STAINED_SOUL_GLASS_PANE);
	public static final RegistryObject<Item> BLACK_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.BLACK_STAINED_SOUL_GLASS);
	public static final RegistryObject<Item> BLACK_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.BLACK_STAINED_SOUL_GLASS_PANE);
	public static final RegistryObject<Item> RED_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.RED_STAINED_SOUL_GLASS);
	public static final RegistryObject<Item> RED_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.RED_STAINED_SOUL_GLASS_PANE);
	public static final RegistryObject<Item> ORANGE_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.ORANGE_STAINED_SOUL_GLASS);
	public static final RegistryObject<Item> ORANGE_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.ORANGE_STAINED_SOUL_GLASS_PANE);
	public static final RegistryObject<Item> YELLOW_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.YELLOW_STAINED_SOUL_GLASS);
	public static final RegistryObject<Item> YELLOW_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.YELLOW_STAINED_SOUL_GLASS_PANE);
	public static final RegistryObject<Item> LIME_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.LIME_STAINED_SOUL_GLASS);
	public static final RegistryObject<Item> LIME_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.LIME_STAINED_SOUL_GLASS_PANE);
	public static final RegistryObject<Item> GREEN_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.GREEN_STAINED_SOUL_GLASS);
	public static final RegistryObject<Item> GREEN_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.GREEN_STAINED_SOUL_GLASS_PANE);
	public static final RegistryObject<Item> CYAN_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.CYAN_STAINED_SOUL_GLASS);
	public static final RegistryObject<Item> CYAN_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.CYAN_STAINED_SOUL_GLASS_PANE);
	public static final RegistryObject<Item> LIGHT_BLUE_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.LIGHT_BLUE_STAINED_SOUL_GLASS);
	public static final RegistryObject<Item> LIGHT_BLUE_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.LIGHT_BLUE_STAINED_SOUL_GLASS_PANE);
	public static final RegistryObject<Item> BLUE_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.BLUE_STAINED_SOUL_GLASS);
	public static final RegistryObject<Item> BLUE_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.BLUE_STAINED_SOUL_GLASS_PANE);
	public static final RegistryObject<Item> PURPLE_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.PURPLE_STAINED_SOUL_GLASS);
	public static final RegistryObject<Item> PURPLE_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.PURPLE_STAINED_SOUL_GLASS_PANE);
	public static final RegistryObject<Item> MAGENTA_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.MAGENTA_STAINED_SOUL_GLASS);
	public static final RegistryObject<Item> MAGENTA_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.MAGENTA_STAINED_SOUL_GLASS_PANE);
	public static final RegistryObject<Item> PINK_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.PINK_STAINED_SOUL_GLASS);
	public static final RegistryObject<Item> PINK_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.PINK_STAINED_SOUL_GLASS_PANE);
	public static final RegistryObject<Item> DARK_GREY_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.DARK_GREY_STAINED_SOUL_GLASS);
	public static final RegistryObject<Item> DARK_GREY_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.DARK_GREY_STAINED_SOUL_GLASS_PANE);
	public static final RegistryObject<Item> BROWN_STAINED_SOUL_GLASS = block(ExtraBuildingBlocksModBlocks.BROWN_STAINED_SOUL_GLASS);
	public static final RegistryObject<Item> BROWN_STAINED_SOUL_GLASS_PANE = block(ExtraBuildingBlocksModBlocks.BROWN_STAINED_SOUL_GLASS_PANE);
	public static final RegistryObject<Item> SANDSTONE_BRICKS = block(ExtraBuildingBlocksModBlocks.SANDSTONE_BRICKS);
	public static final RegistryObject<Item> SANDSTONE_BRICK_STAIRS = block(ExtraBuildingBlocksModBlocks.SANDSTONE_BRICK_STAIRS);
	public static final RegistryObject<Item> SANDSTONE_BRICK_SLAB = block(ExtraBuildingBlocksModBlocks.SANDSTONE_BRICK_SLAB);
	public static final RegistryObject<Item> SANDSTONE_BRICK_WALL = block(ExtraBuildingBlocksModBlocks.SANDSTONE_BRICK_WALL);
	public static final RegistryObject<Item> RED_SANDSTONE_BRICKS = block(ExtraBuildingBlocksModBlocks.RED_SANDSTONE_BRICKS);
	public static final RegistryObject<Item> RED_SANDSTONE_BRICK_STAIRS = block(ExtraBuildingBlocksModBlocks.RED_SANDSTONE_BRICK_STAIRS);
	public static final RegistryObject<Item> RED_SANDSTONE_BRICK_SLAB = block(ExtraBuildingBlocksModBlocks.RED_SANDSTONE_BRICK_SLAB);
	public static final RegistryObject<Item> RED_SANDSTONE_BRICK_WALL = block(ExtraBuildingBlocksModBlocks.RED_SANDSTONE_BRICK_WALL);
	public static final RegistryObject<Item> SOUL_SLATE = block(ExtraBuildingBlocksModBlocks.SOUL_SLATE);
	public static final RegistryObject<Item> SOUL_SLATE_BRICKS = block(ExtraBuildingBlocksModBlocks.SOUL_SLATE_BRICKS);
	public static final RegistryObject<Item> CHISELED_SOUL_SLATE = block(ExtraBuildingBlocksModBlocks.CHISELED_SOUL_SLATE);
	public static final RegistryObject<Item> SOUL_SLATE_BRICK_STAIRS = block(ExtraBuildingBlocksModBlocks.SOUL_SLATE_BRICK_STAIRS);
	public static final RegistryObject<Item> SOUL_SLATE_BRICK_SLAB = block(ExtraBuildingBlocksModBlocks.SOUL_SLATE_BRICK_SLAB);
	public static final RegistryObject<Item> SOUL_SLATE_BRICK_WALL = block(ExtraBuildingBlocksModBlocks.SOUL_SLATE_BRICK_WALL);
	public static final RegistryObject<Item> PURPUR_WALL = block(ExtraBuildingBlocksModBlocks.PURPUR_WALL);
	public static final RegistryObject<Item> ECHO_CRYSTAL = block(ExtraBuildingBlocksModBlocks.ECHO_CRYSTAL);
	public static final RegistryObject<Item> CHISELED_END_STONE_BRICKS = block(ExtraBuildingBlocksModBlocks.CHISELED_END_STONE_BRICKS);
	public static final RegistryObject<Item> HANGING_TORCHFLOWER = block(ExtraBuildingBlocksModBlocks.HANGING_TORCHFLOWER);
	public static final RegistryObject<Item> RAW_SALT = block(ExtraBuildingBlocksModBlocks.RAW_SALT);
	public static final RegistryObject<Item> SALT_CRYSTAL = block(ExtraBuildingBlocksModBlocks.SALT_CRYSTAL);
	public static final RegistryObject<Item> SALT_GROWTH = block(ExtraBuildingBlocksModBlocks.SALT_GROWTH);
	public static final RegistryObject<Item> WROUGHT_IRON = block(ExtraBuildingBlocksModBlocks.WROUGHT_IRON);
	public static final RegistryObject<Item> STONE_PILLAR = block(ExtraBuildingBlocksModBlocks.STONE_PILLAR);
	public static final RegistryObject<Item> CHISELED_RED_NETHER_BRICK = block(ExtraBuildingBlocksModBlocks.CHISELED_RED_NETHER_BRICK);
	public static final RegistryObject<Item> CACTUS_WOOD = block(ExtraBuildingBlocksModBlocks.CACTUS_WOOD);
	public static final RegistryObject<Item> CACTUS_W_PLANKS = block(ExtraBuildingBlocksModBlocks.CACTUS_W_PLANKS);
	public static final RegistryObject<Item> CACTUS_W_STAIRS = block(ExtraBuildingBlocksModBlocks.CACTUS_W_STAIRS);
	public static final RegistryObject<Item> CACTUS_W_SLAB = block(ExtraBuildingBlocksModBlocks.CACTUS_W_SLAB);
	public static final RegistryObject<Item> CACTUS_W_FENCE = block(ExtraBuildingBlocksModBlocks.CACTUS_W_FENCE);
	public static final RegistryObject<Item> CACTUS_W_FENCE_GATE = block(ExtraBuildingBlocksModBlocks.CACTUS_W_FENCE_GATE);
	public static final RegistryObject<Item> CACTUS_W_PRESSURE_PLATE = block(ExtraBuildingBlocksModBlocks.CACTUS_W_PRESSURE_PLATE);
	public static final RegistryObject<Item> CACTUS_W_BUTTON = block(ExtraBuildingBlocksModBlocks.CACTUS_W_BUTTON);
	public static final RegistryObject<Item> POTTED_CHORUS = block(ExtraBuildingBlocksModBlocks.POTTED_CHORUS);
	public static final RegistryObject<Item> VERY_CRACKED_STONE_BRICKS = block(ExtraBuildingBlocksModBlocks.VERY_CRACKED_STONE_BRICKS);
	public static final RegistryObject<Item> DESTROYED_STONE_BRICKS = block(ExtraBuildingBlocksModBlocks.DESTROYED_STONE_BRICKS);
	public static final RegistryObject<Item> CRACKED_BRICKS = block(ExtraBuildingBlocksModBlocks.CRACKED_BRICKS);
	public static final RegistryObject<Item> VERY_CRACKED_BRICKS = block(ExtraBuildingBlocksModBlocks.VERY_CRACKED_BRICKS);
	public static final RegistryObject<Item> DESTROYED_BRICKS = block(ExtraBuildingBlocksModBlocks.DESTROYED_BRICKS);
	public static final RegistryObject<Item> MOSSY_BRICKS = block(ExtraBuildingBlocksModBlocks.MOSSY_BRICKS);
	public static final RegistryObject<Item> CACTUS_WOOD_DOOR = doubleBlock(ExtraBuildingBlocksModBlocks.CACTUS_WOOD_DOOR);
	public static final RegistryObject<Item> CACTUS_WOOD_TRAPDOOR = block(ExtraBuildingBlocksModBlocks.CACTUS_WOOD_TRAPDOOR);
	public static final RegistryObject<Item> LACE_BANNER = block(ExtraBuildingBlocksModBlocks.LACE_BANNER);
	public static final RegistryObject<Item> LACE = REGISTRY.register("lace", () -> new LaceItem());
	public static final RegistryObject<Item> WHITE_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.WHITE_LACE_BANNER);
	public static final RegistryObject<Item> LIGHT_GREY_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.LIGHT_GREY_LACE_BANNER);
	public static final RegistryObject<Item> GREY_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.GREY_LACE_BANNER);
	public static final RegistryObject<Item> BLACK_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.BLACK_LACE_BANNER);
	public static final RegistryObject<Item> RED_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.RED_LACE_BANNER);
	public static final RegistryObject<Item> ORANGE_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.ORANGE_LACE_BANNER);
	public static final RegistryObject<Item> YELLOW_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.YELLOW_LACE_BANNER);
	public static final RegistryObject<Item> LIME_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.LIME_LACE_BANNER);
	public static final RegistryObject<Item> GREEN_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.GREEN_LACE_BANNER);
	public static final RegistryObject<Item> CYAN_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.CYAN_LACE_BANNER);
	public static final RegistryObject<Item> LIGHT_BLUE_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.LIGHT_BLUE_LACE_BANNER);
	public static final RegistryObject<Item> BLUE_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.BLUE_LACE_BANNER);
	public static final RegistryObject<Item> PURPLE_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.PURPLE_LACE_BANNER);
	public static final RegistryObject<Item> MAGENTA_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.MAGENTA_LACE_BANNER);
	public static final RegistryObject<Item> PINK_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.PINK_LACE_BANNER);
	public static final RegistryObject<Item> BROWN_LACE_BANNER = block(ExtraBuildingBlocksModBlocks.BROWN_LACE_BANNER);
	public static final RegistryObject<Item> PRISMARINE_BRICK_WALL = block(ExtraBuildingBlocksModBlocks.PRISMARINE_BRICK_WALL);
	public static final RegistryObject<Item> DARK_PRISMARINE_WALL = block(ExtraBuildingBlocksModBlocks.DARK_PRISMARINE_WALL);
	public static final RegistryObject<Item> PRISMARINE_PILLAR = block(ExtraBuildingBlocksModBlocks.PRISMARINE_PILLAR);
	public static final RegistryObject<Item> DARK_PRISMARINE_PILLAR = block(ExtraBuildingBlocksModBlocks.DARK_PRISMARINE_PILLAR);
	public static final RegistryObject<Item> CHISELED_PRISMARINE = block(ExtraBuildingBlocksModBlocks.CHISELED_PRISMARINE);
	public static final RegistryObject<Item> SALT_CRYSTAL_EMISSIVE = block(ExtraBuildingBlocksModBlocks.SALT_CRYSTAL_EMISSIVE);
	public static final RegistryObject<Item> SOUL_MAGMA = block(ExtraBuildingBlocksModBlocks.SOUL_MAGMA);
	public static final RegistryObject<Item> RED_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.RED_LACE_CARPET);
	public static final RegistryObject<Item> ORANGE_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.ORANGE_LACE_CARPET);
	public static final RegistryObject<Item> YELLOW_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.YELLOW_LACE_CARPET);
	public static final RegistryObject<Item> LIME_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.LIME_LACE_CARPET);
	public static final RegistryObject<Item> GREEN_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.GREEN_LACE_CARPET);
	public static final RegistryObject<Item> CYAN_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.CYAN_LACE_CARPET);
	public static final RegistryObject<Item> LIGHT_BLUE_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.LIGHT_BLUE_LACE_CARPET);
	public static final RegistryObject<Item> BLUE_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.BLUE_LACE_CARPET);
	public static final RegistryObject<Item> PURPLE_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.PURPLE_LACE_CARPET);
	public static final RegistryObject<Item> MAGENTA_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.MAGENTA_LACE_CARPET);
	public static final RegistryObject<Item> PINK_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.PINK_LACE_CARPET);
	public static final RegistryObject<Item> BROWN_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.BROWN_LACE_CARPET);
	public static final RegistryObject<Item> BLACK_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.BLACK_LACE_CARPET);
	public static final RegistryObject<Item> GREY_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.GREY_LACE_CARPET);
	public static final RegistryObject<Item> LIGHT_GREY_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.LIGHT_GREY_LACE_CARPET);
	public static final RegistryObject<Item> WHITE_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.WHITE_LACE_CARPET);
	public static final RegistryObject<Item> BUS_LACE_CARPET = block(ExtraBuildingBlocksModBlocks.BUS_LACE_CARPET);
	public static final RegistryObject<Item> LACE_CARPET = block(ExtraBuildingBlocksModBlocks.LACE_CARPET);
	public static final RegistryObject<Item> CHISELED_STONE = block(ExtraBuildingBlocksModBlocks.CHISELED_STONE);
	public static final RegistryObject<Item> CHISELED_DEEPSLATE_BRICKS = block(ExtraBuildingBlocksModBlocks.CHISELED_DEEPSLATE_BRICKS);
	public static final RegistryObject<Item> CHISELED_BLACKSTONE_BRICKS = block(ExtraBuildingBlocksModBlocks.CHISELED_BLACKSTONE_BRICKS);
	public static final RegistryObject<Item> HOOK = block(ExtraBuildingBlocksModBlocks.HOOK);
	public static final RegistryObject<Item> DUCK_WEED = block(ExtraBuildingBlocksModBlocks.DUCK_WEED);
	public static final RegistryObject<Item> FOUNTAIN_GRASS = block(ExtraBuildingBlocksModBlocks.FOUNTAIN_GRASS);
	public static final RegistryObject<Item> PURPLE_FOUNTAIN_GRASS = block(ExtraBuildingBlocksModBlocks.PURPLE_FOUNTAIN_GRASS);
	public static final RegistryObject<Item> SWAMP_GRASS = block(ExtraBuildingBlocksModBlocks.SWAMP_GRASS);
	public static final RegistryObject<Item> GREEN_DESERT_BUSH = block(ExtraBuildingBlocksModBlocks.GREEN_DESERT_BUSH);
	public static final RegistryObject<Item> PURPLE_DESERT_BUSH = block(ExtraBuildingBlocksModBlocks.PURPLE_DESERT_BUSH);
	public static final RegistryObject<Item> BRACE = block(ExtraBuildingBlocksModBlocks.BRACE);
	public static final RegistryObject<Item> COPPER_BARS = block(ExtraBuildingBlocksModBlocks.COPPER_BARS);
	public static final RegistryObject<Item> EXPOSED_COPPER_BARS = block(ExtraBuildingBlocksModBlocks.EXPOSED_COPPER_BARS);
	public static final RegistryObject<Item> WEATHERED_COPPER_BARS = block(ExtraBuildingBlocksModBlocks.WEATHERED_COPPER_BARS);
	public static final RegistryObject<Item> OXIDISED_COPPER_BARS = block(ExtraBuildingBlocksModBlocks.OXIDISED_COPPER_BARS);
	public static final RegistryObject<Item> IRON_GATE = block(ExtraBuildingBlocksModBlocks.IRON_GATE);
	public static final RegistryObject<Item> WEATHERED_WROUGHT_IRON = block(ExtraBuildingBlocksModBlocks.WEATHERED_WROUGHT_IRON);
	public static final RegistryObject<Item> WROUGHT_IRON_BARS = block(ExtraBuildingBlocksModBlocks.WROUGHT_IRON_BARS);
	public static final RegistryObject<Item> FROSTED_GLASS = block(ExtraBuildingBlocksModBlocks.FROSTED_GLASS);
	public static final RegistryObject<Item> RUSTED_WROUGHT_IRON = block(ExtraBuildingBlocksModBlocks.RUSTED_WROUGHT_IRON);
	public static final RegistryObject<Item> EXPOSED_WROUGHT_IRON = block(ExtraBuildingBlocksModBlocks.EXPOSED_WROUGHT_IRON);
	public static final RegistryObject<Item> STONE_WALL = block(ExtraBuildingBlocksModBlocks.STONE_WALL);
	public static final RegistryObject<Item> DARK_SEA_LANTERN = block(ExtraBuildingBlocksModBlocks.DARK_SEA_LANTERN);
	public static final RegistryObject<Item> WROUGHT_IRON_GATE = block(ExtraBuildingBlocksModBlocks.WROUGHT_IRON_GATE);
	public static final RegistryObject<Item> WAXED_WROUGHT_IRON = block(ExtraBuildingBlocksModBlocks.WAXED_WROUGHT_IRON);
	public static final RegistryObject<Item> WAXED_WEATHERED_WROUGHT_IRON = block(ExtraBuildingBlocksModBlocks.WAXED_WEATHERED_WROUGHT_IRON);
	public static final RegistryObject<Item> WAXED_EXPOSED_WROUGHT_IRON = block(ExtraBuildingBlocksModBlocks.WAXED_EXPOSED_WROUGHT_IRON);
	public static final RegistryObject<Item> WAXED_RUSTED_WROUGHT_IRON = block(ExtraBuildingBlocksModBlocks.WAXED_RUSTED_WROUGHT_IRON);
	public static final RegistryObject<Item> WAXED_COPPER_BARS = block(ExtraBuildingBlocksModBlocks.WAXED_COPPER_BARS);
	public static final RegistryObject<Item> WAXED_EXPOSED_COPPER_BARS = block(ExtraBuildingBlocksModBlocks.WAXED_EXPOSED_COPPER_BARS);
	public static final RegistryObject<Item> WAXED_WEATHERED_COPPER_BARS = block(ExtraBuildingBlocksModBlocks.WAXED_WEATHERED_COPPER_BARS);
	public static final RegistryObject<Item> WAXED_OXIDISED_COPPER_BARS = block(ExtraBuildingBlocksModBlocks.WAXED_OXIDISED_COPPER_BARS);
	public static final RegistryObject<Item> EXPOSED_WROUGHT_IRON_BARS = block(ExtraBuildingBlocksModBlocks.EXPOSED_WROUGHT_IRON_BARS);
	public static final RegistryObject<Item> WEATHERED_WROUGHT_IRON_BARS = block(ExtraBuildingBlocksModBlocks.WEATHERED_WROUGHT_IRON_BARS);
	public static final RegistryObject<Item> RUSTED_WROUGHT_IRON_BARS = block(ExtraBuildingBlocksModBlocks.RUSTED_WROUGHT_IRON_BARS);
	public static final RegistryObject<Item> WAXED_WROUGHT_IRON_BARS = block(ExtraBuildingBlocksModBlocks.WAXED_WROUGHT_IRON_BARS);
	public static final RegistryObject<Item> WAXED_WEATHERED_WROUGHT_IRON_BARS = block(ExtraBuildingBlocksModBlocks.WAXED_WEATHERED_WROUGHT_IRON_BARS);
	public static final RegistryObject<Item> WAXED_EXPOSED_WROUGHT_IRON_BARS = block(ExtraBuildingBlocksModBlocks.WAXED_EXPOSED_WROUGHT_IRON_BARS);
	public static final RegistryObject<Item> WAXED_RUSTED_WROUGHT_IRON_BARS = block(ExtraBuildingBlocksModBlocks.WAXED_RUSTED_WROUGHT_IRON_BARS);

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
